insert into lists (name, list, active) VALUES ('14 - Itau', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('0 - República ', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('3 - Coofinep', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('8 - ABN Amor Bank', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('18 - Corficolombiana', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('19 - Scotiabank Colpatria', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('32 - BCSC Caja Social', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('36 - Nequi', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('37 - Daviplata', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('53 - Banco W S.A', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('56 - Banco WWB S.A', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('59 - Bancamia', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('64 - Banco Multibank', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('67 - Banco Compartir', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('262 - IDEA', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('283 - Cooperativa Financiera de Antioquia', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('289 - Cotrafa', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('296 - Financiera Juriscoop', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('318 - Cofincafe', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('370 - Coltefinanciera S.A', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('700 - Cooperativa San Pio X Coogran', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('701 - Cooperativa San Pio XII de Cocorna', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('811 - Fondo Nacional del Ahorro', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('812 - Leasing de Crédito S.A', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('816 - Confiar', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('857 - Giros y Finanzas', 'BANK', TRUE);
update lists set name = '40 - Agrario de Colombia' where name = 'Agrario de Colombia';
update lists set name = '52 - Av Villas' where name = 'Av Villas';
update lists set name = '13 - BBVA' where name = 'BBVA';
update lists set name = '1 - Bogotá' where name = 'Bogotá';
update lists set name = '9 - Citibank' where name = 'Citibank';
update lists set name = '66 - Coopcentral' where name = 'Coopcentral';
update lists set name = '51 - Davivienda' where name = 'Davivienda';
update lists set name = '23 - Occidente' where name = 'Occidente';
update lists set name = '62 - Falabella' where name = 'Falabella';
update lists set name = '63 - Finandina' where name = 'Finandina';
update lists set name = '12 - GNB Sudameris' where name = 'GNB Sudameris';
update lists set name = '6 - Itaú Corbanca' where name = 'Itaú Corbanca';
update lists set name = '47 - Mundo Mujer' where name = 'Mundo Mujer';
update lists set name = '60 - Pichincha' where name = 'Pichincha';
update lists set name = '2 - Popular' where name = 'Popular';
update lists set name = '58 - Credifinanciera' where name = 'Credifinanciera';
update lists set name = '65 - Santander' where name = 'Santander';
update lists set name = '855 - Serfinanzas' where name = 'Serfinanzas';
update lists set name = '856 - Bancoldex' where name = 'Bancoldex';
update lists set name = '7 - Bancolombia' where name = 'Bancolombia';
update lists set name = '61 - Bancomeva' where name = 'Bancomeva';
update lists set name = '858 - BNP Paribas' where name = 'BNP Paribas';
COMMIT;