UPDATE lists set name = '1302 - ABEJORRAL - Antioquia' WHERE name = 'Sucursal Norte';
UPDATE lists set name = '5111 - ABREGO - Norte de Santander' WHERE name = 'Sucursal Sur';
UPDATE lists set name = '4503 - ACACIAS - Meta' WHERE name = 'Sucursal Este';
UPDATE lists set name = '3301 - ACANDI - Chocó' WHERE name = 'Sucursal Oeste';

INSERT INTO lists (name, list, active) VALUES ('3901 - ACEVEDO - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1203 - ACHI - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3902 - AGRADO - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3110 - AGUA DE DIOS - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2401 - AGUACHICA - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1801 - AGUADAS - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8601 - AGUAZUL - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3908 - AIPE - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7501 - ALBANIA - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6901 - ALCALA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1471 - ALEJANDRIA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3903 - ALGECIRAS - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2171 - ALMAGUER - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6623 - ALPUJARRA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3909 - ALTAMIRA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1334 - ALTAMIRA (Corregimiento del municipio de Betulia - Antioquia) - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6605 - ALVARADO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1350 - AMAGA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3106 - ANAPOIMA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4811 - ANCUYA - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1301 - ANDES - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1309 - ANGELOPOLIS - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1314 - ANGOSTURA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3107 - ANOLAIMA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1316 - ANORI - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1825 - ANSERMA - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6935 - ANSERMANUEVO - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1317 - ANZA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6627 - ANZOATEGUI - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1352 - APARTADO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5740 - APIA - Risaralda', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3109 - APULO - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1501 - AQUITANIA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4212 - ARACATACA - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1850 - ARANZAZU - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6010 - ARATOCA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7303 - ARAUCA - Arauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1840 - ARAUCA ( Corregimiento del municipio de Palestina - Caldas) Operando desde Oficina Risaralda - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7305 - ARAUQUITA - Arauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3113 - ARBELAEZ - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5112 - ARBOLEDAS - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1318 - ARBOLETES - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1502 - ARCABUCO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1330 - ARGELIA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2115 - ARGELIA - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1215 - ARJONA - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1349 - ARMENIA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5401 - ARMENIA - Quindio', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2402 - ASTREA - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6649 - ATACO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2701 - AYAPEL - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3309 - BAHIA SOLANO - Chocó', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5725 - BALBOA - Risaralda', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2103 - BALBOA - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1622 - BARANOA - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3912 - BARAYA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4860 - BARBACOAS - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6024 - BARBOSA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5430 - BARCELONA (Corregimiento del municipio de Calarcá - Quindio ) - Quindio', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6025 - BARICHARA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6020 - BARRANCABERMEJA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1601 - BARRANQUILLA ( PRINCIPAL ) - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1610 - BARRANQUILLA PRADO - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2405 - BECERRIL - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1820 - BELALCAZAR - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4834 - BELEN - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1504 - BELEN - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7510 - BELEN DE LOS ANDAQUIES - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5746 - BELEN DE UMBRIA(Operando desde la oficina de Viterbo-Caldas) - Risaralda', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1351 - BELLO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4890 - BERRUECOS - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1341 - BETANIA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6027 - BETULIA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1506 - BOAVITA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4864 - BOCAS DE SATINGA - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5108 - BOCHALEMA(Operando desde la oficina de Cucuta-Norte Santander con el horario de Cucuta mientras dure la contingencia) - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('820 - BOGOTA - AVENIDA CHILE - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('70 - BOGOTA - AVENIDA JIMENEZ - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('590 - BOGOTA - BARRIO RESTREPO - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('360 - BOGOTÀ - CALLE CIEN - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('230 - BOGOTA - CAN - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('280 - BOGOTA - CODABAS - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('260 - BOGOTA - CORABASTOS - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3192 - BOGOTA - GOBERNACION DE CUND. - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('250 - BOGOTA - PALOQUEMAO - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('850 - BOGOTA - PUENTE ARANDA - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('890 - BOGOTA - USME - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('20 - BOGOTA CENTRO DE PAGOS, RECAUDOS Y DEPOSITOS JUDICIALES CHAPINERO - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1342 - BOLIVAR - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6924 - BOLIVAR - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2104 - BOLIVAR - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6029 - BOLIVAR - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1822 - BOLIVIA (Corregimiento de l municipio de Pensilvania - Caldas) - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2414 - BOSCONIA - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3943 - BRUSELAS (Corregimiento de Pitalito - Huila) - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6001 - BUCARAMANGA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6963 - BUENAVENTURA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2712 - BUENAVISTA - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5455 - BUENAVISTA - Quindio', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6305 - BUENAVISTA - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2128 - BUENOS AIRES - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4866 - BUESACO - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3111 - CABRERA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4510 - CABUYARO - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3115 - CACHIPAY - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5121 - CACHIRA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5119 - CACOTA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1354 - CAICEDO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5412 - CAICEDONIA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6310 - CAIMITO - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6607 - CAJAMARCA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2105 - CAJIBIO - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1216 - CALAMAR - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5410 - CALARCA - Quindio', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1375 - CALDAS - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2110 - CALDONO - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6915 - CALI AVENIDA TERCERA NORTE - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6925 - CALI PASOANCHO - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6903 - CALI SUCURSAL - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2118 - CALOTO - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1361 - CAMPAMENTO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1626 - CAMPO DE LA CRUZ - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3914 - CAMPOALEGRE - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1509 - CAMPOHERMOSO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2717 - CANALETE - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1654 - CANDELARIA - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6971 - CANDELARIA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6975 - CANDELARIA - CAVASA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1362 - CAÑASGORDAS - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3117 - CAPARRAPI - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6033 - CAPITANEJO - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3114 - CAQUEZA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1410 - CARACOLI - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1412 - CARAMANTA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6035 - CARCASI - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6640 - CARMEN DE APICALA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3315 - CARMEN DE ATRATO - Chocó', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3127 - CARMEN DE CARUPA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1374 - CARMEN DE VIBORAL - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1414 - CAROLINA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1207 - CARTAGENA - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7514 - CARTAGENA DEL CHAIRA - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6978 - CARTAGO - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6626 - CASABIANCA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4509 - CASTILLA LA NUEVA - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1321 - CAUCASIA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6012 - CENTRAL DE ABASTOS BUCARAMANGA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5113 - CENTRAL DE ABASTOS CUCUTA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3916 - CENTRAL DE ABASTOS NEIVA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5704 - CENTRAL DE ABASTOS PEREIRA - Risaralda', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6315 - CENTRAL DE ABASTOS SINCELEJO - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('10 - CENTRO DE NEGOCIOS BOGOTA CENTRO - Bogotá D.C', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1323 - CENTRO DE NEGOCIOS MEDELLIN CARABOBO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2715 - CERETE - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6037 - CERRITO - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4203 - CERRO DE SAN ANTONIO - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4845 - CHACHAGÜI - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3120 - CHAGUANI - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6613 - CHAPARRAL - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6014 - CHARALÁ - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('920 - CHIA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1325 - CHIGORODO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2721 - CHIMA - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6045 - CHIMA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2416 - CHIMICHAGUA - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5115 - CHINACOTA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1512 - CHINAVITA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6074 - CHIPATA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1530 - CHIQUINQUIRA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2422 - CHIRIGUANA - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1514 - CHISCAS - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1518 - CHITA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5122 - CHITAGA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1520 - CHITARAQUE - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4205 - CHIVOLO - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1515 - CHIVOR - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3116 - CHOACHI - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3118 - CHOCONTA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4209 - CIENAGA - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2719 - CIENAGA DE ORO - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6026 - CIMITARRA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5415 - CIRCASIA - Quindio', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1368 - CISNEROS - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1372 - COCORNA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2408 - CODAZZI - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6631 - COELLO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3910 - COLOMBIA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1401 - CONCEPCION - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6039 - CONCEPCION - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3320 - CONDOTO - Chocó', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4884 - CONSACA - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4818 - CONTADERO - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6041 - CONTRATACION - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5116 - CONVENCION - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1355 - COPACABANA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5440 - CORDOBA - Quindio', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4805 - CORDOBA - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2114 - CORINTO - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6043 - COROMORO - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6314 - COROZAL - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1522 - COVARACHIA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6633 - COYAIMA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7310 - CRAVO NORTE - Arauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1510 - CUBARA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4505 - CUBARRAL - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5101 - CUCUTA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5117 - CUCUTILLA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4507 - CUMARAL - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8505 - CUMARIBO - Vichada', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4814 - CUMBAL - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4824 - CUMBITARA - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6634 - CUNDAY - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3915 - CURILLO - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6030 - CURITI - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1428 - DABEIBA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6976 - DAGUA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6964 - DARIEN - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6648 - DOLORES - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1324 - DON MATIAS - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5712 - DOSQUEBRADAS - Risaralda', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1507 - DUITAMA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5114 - DURANIA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1353 - EBEJICO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6926 - EL AGUILA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1320 - EL BAGRE - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4220 - EL BANCO - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2102 - EL BORDO - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5123 - EL CARMEN - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1230 - EL CARMEN DE BOLIVAR - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6080 - EL CARMEN DE CHUCURI - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4512 - EL CASTILLO - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6965 - EL CERRITO - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4826 - EL CHARCO - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1524 - EL COCUY - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3124 - EL COLEGIO - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2427 - EL COPEY - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4223 - EL DIFICIL - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7520 - EL DONCELLO - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1526 - EL ESPINO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7525 - EL PAUJIL - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1448 - EL PEÑOL - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1348 - EL RETIRO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4828 - EL ROSARIO - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4875 - EL TABLON DE GOMEZ - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2101 - EL TAMBO - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4830 - EL TAMBO - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5110 - EL ZULIA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3921 - ELIAS - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1359 - ENVIGADO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6635 - ESPINAL - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('900 - FACATATIVA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6622 - FALAN - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5445 - FILANDIA - Quindio', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7503 - FLORENCIA - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6050 - FLORIAN - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6943 - FLORIDA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6015 - FLORIDABLANCA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3130 - FOMEQUE - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2413 - FONSECA - La Guajira', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7315 - FORTUL - Arauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3126 - FOSCA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6651 - FRESNO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1420 - FRONTINO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4514 - FUENTE DE ORO - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4832 - FUNES - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('910 - FUNZA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3166 - FUSAGASUGA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3134 - GACHALA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1528 - GACHANTIVA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3135 - GACHETA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6320 - GALERAS - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6052 - GAMBITA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1532 - GAMEZA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1534 - GARAGOA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3913 - GARZON - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3918 - GIGANTE - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6913 - GINEBRA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3122 - GIRARDOT - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1377 - GIRARDOTA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6011 - GIRON - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1422 - GOMEZ PLATA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5125 - GRAMALOTE - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1380 - GRANADA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4517 - GRANADA - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6053 - GUACA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6967 - GUACARI - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4816 - GUACHUCAL - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6977 - GUADALAJARA DE BUGA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1378 - GUADALUPE - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6054 - GUADALUPE - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3920 - GUADALUPE - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3133 - GUADUAS - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4836 - GUAITARILLA - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4515 - GUAMAL - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4230 - GUAMAL - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6617 - GUAMO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2125 - GUAPI - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6324 - GUARANDA - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1379 - GUARNE - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3136 - GUASCA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3137 - GUATAVITA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1536 - GUATEQUE - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5765 - GUATICA - Risaralda', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6055 - GUAVATA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6630 - GUAYABAL - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3138 - GUAYABAL DE SIQUIMA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1538 - GUAYATA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6056 - GUEPSA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1540 - GUICAN - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3139 - GUTIERREZ - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5126 - HACARI - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8610 - HATO COROZAL - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1360 - HELICONIA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5127 - HERRAN - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6639 - HERRERA Corregimiento (Del Municipio de Rioblanco - Tolima) - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6614 - HERVEO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3922 - HOBO - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6610 - HONDA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6601 - IBAGUE - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6609 - ICONONZO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4838 - ILES - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2120 - INZA - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4806 - IPIALES - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3935 - IQUIRA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3937 - ISNOS - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1305 - ITAGÜI - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1424 - ITUANGO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2132 - JAMBALO - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6928 - JAMUNDÍ - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1336 - JARDIN - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1535 - JENESANO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1393 - JERICO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6057 - JESUS MARIA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1648 - JUAN DE ACOSTA - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3140 - JUNIN - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3928 - LA ARGENTINA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6058 - LA BELLEZA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('700 - LA CALERA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1370 - LA CEJA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5732 - LA CELIA - Risaralda', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4840 - LA CRUZ - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6931 - LA CUMBRE - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5413 - LA DORADA - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1371 - LA ESTRELLA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2437 - LA GLORIA - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7910 - LA HORMIGA - Putumayo', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2442 - LA JAGUA DE IBIRICO - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4519 - LA MACARENA - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1846 - LA MERCED - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3142 - LA MESA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7540 - LA MONTAÑITA - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3143 - LA PALMA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6060 - LA PAZ - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2412 - LA PAZ ROBLES - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3144 - LA PEÑA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1363 - LA PINTADA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3927 - LA PLATA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8510 - LA PRIMAVERA - Vichada', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2109 - LA SIERRA - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5425 - LA TEBAIDA - Quindio', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1382 - LA UNION - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6330 - LA UNION - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4842 - LA UNION - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5414 - LA UNION - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1544 - LA UVITA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3145 - LA VEGA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2172 - LA VEGA - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5118 - LABATECA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1542 - LABRANZAGRANDE - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6062 - LANDAZURI - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6013 - LEBRIJA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4518 - LEJANIAS - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3141 - LENGUAZAQUE - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6606 - LÉRIDA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7103 - LETICIA - Amazonas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6638 - LIBANO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1426 - LIBORINA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4844 - LINARES - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2139 - LOPEZ DE MICAY - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2745 - LORICA - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2747 - LOS CORDOBAS - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6335 - LOS PALMITOS - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6063 - LOS SANTOS - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5134 - LOURDES - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1630 - LURUACO - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1548 - MACANAL - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1435 - MACEO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3146 - MACHETA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1240 - MAGANGUE - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3630 - MAICAO - La Guajira', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6340 - MAJAGUAL - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6032 - MALAGA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1634 - MANATI - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3620 - MANAURE - La Guajira', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2420 - MANAURE - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8615 - MANI - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1803 - MANIZALES - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3147 - MANTA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4543 - MAPIRIPAN - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1218 - MARIA LA BAJA - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1383 - MARINILLA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6608 - MARIQUITA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1832 - MARMATO - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1833 - MARQUETALIA - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1834 - MARULANDA - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6064 - MATANZA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1331 - MEDELLIN ALPUJARRA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1307 - MEDELLIN AMERICA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1303 - MEDELLIN MILLA DE ORO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3148 - MEDINA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2116 - MERCADERES - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4521 - MESETAS - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7545 - MILAN - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8315 - MIRAFLORES - Guaviare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1550 - MIRAFLORES - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2112 - MIRANDA - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5750 - MISTRATO - Risaralda', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8420 - MITU - Vaupés', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7903 - MOCOA - Putumayo', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6065 - MOGOTES - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6066 - MOLAGAVITA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2750 - MOMIL - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1243 - MOMPOX - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1551 - MONIQUIRA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1438 - MONTEBELLO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2752 - MONTELIBANO - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2703 - MONTERIA - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8620 - MONTERREY - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2754 - MOÑITOS - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2106 - MORALES - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1244 - MORALES - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6618 - MURILLO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1326 - MUTATA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5136 - MUTISCUA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1545 - MUZO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6932 - NARANJAL (Corregimiento del municipio de Bolivar - Valle del Cauca) - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1442 - NARIÑO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3932 - NATAGA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6619 - NATAGAIMA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1444 - NECHI - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1446 - NECOCLI - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1812 - NEIRA - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3905 - NEIVA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3149 - NOCAIMA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1861 - NORCASIA - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1547 - NUEVO COLON - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8623 - NUNCHIA - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5120 - OCAÑA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6016 - OIBA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6067 - ONZAGA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3947 - OPORAPA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7920 - ORITO - Putumayo', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8630 - OROCUE - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6621 - ORTEGA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1552 - OTANCHE - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6350 - OVEJAS - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3195 - PACHO - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1860 - PACORA - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2126 - PADILLA - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1553 - PAEZ - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2140 - PAEZ BELALCAZAR - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3923 - PAICOL - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2455 - PAILITAS - CESAR - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3152 - PAIME - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1511 - PAIPA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2134 - PAISPAMBA SOTARA - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1554 - PAJARITO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3925 - PALERMO - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3945 - PALESTINA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6940 - PALMIRA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6624 - PALOCABILDO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5130 - PAMPLONA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3162 - PANDI - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8635 - PARATEBUENO - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3153 - PASCA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4801 - PASTO - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1555 - PAUNA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8645 - PAZ DE ARIPORO - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1505 - PAZ DE RIO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2460 - PELAYA - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1450 - PEQUE - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5703 - PEREIRA - Risaralda', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1556 - PESCA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6017 - PIEDECUESTA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6641 - PIEDRAS - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6922 - PIENDAMO - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5462 - PIJAO - Quindio', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1246 - PINILLOS - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3963 - PITAL - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3942 - PITALITO - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4240 - PIVIJAY - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3350 - PIZARRO - Chocó', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6642 - PLANADAS - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2765 - PLANETA RICA - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4244 - PLATO - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4891 - POLICARPA - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6918 - POPAYAN - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8646 - PORE - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6941 - PRADERA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6645 - PRADO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8110 - PROVIDENCIA - Archipiélago de San Andrés, Providencia y Santa Catalina', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2767 - PUEBLO NUEVO - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5755 - PUEBLO RICO - Risaralda', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1452 - PUEBLORRICO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4820 - PUERRES - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7930 - PUERTO ASIS - Putumayo', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1365 - PUERTO BERRIO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1560 - PUERTO BOYACA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8503 - PUERTO CARREÑO - Vichada', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1652 - PUERTO COLOMBIA - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2769 - PUERTO ESCONDIDO - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4524 - PUERTO GAITAN - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7960 - PUERTO GUZMAN - Putumayo', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7703 - PUERTO INIRIDA - Guainía', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7935 - PUERTO LEGUIZAMO - Putumayo', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2771 - PUERTO LIBERTADOR - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4522 - PUERTO LLERAS - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4530 - PUERTO LOPEZ - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1430 - PUERTO NARE - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4523 - PUERTO RICO - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7560 - PUERTO RICO - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7350 - PUERTO RONDON - Arauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3164 - PUERTO SALGAR - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5105 - PUERTO SANTANDER - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6921 - PUERTO TEJADA - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1366 - PUERTO TRIUNFO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6038 - PUERTO WILCHES - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4812 - PUPIALES - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2174 - PURACE - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6625 - PURIFICACION - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2773 - PURISIMA (Operando desde la oficina de Lorica - Córdoba) - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3154 - QUETAME - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3303 - QUIBDO - Chocó', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5420 - QUIMBAYA - Quindio', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3155 - QUIPILE - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5145 - RAGONVALIA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1563 - RAMIRIQUI - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1454 - REMEDIOS( Operando desde Oficina Segovia) - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1636 - REPELON - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4525 - RESTREPO - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4868 - RICAURTE - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2465 - RIO DE ORO - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6646 - RIOBLANCO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6954 - RIOFRIO - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3603 - RIOHACHA - La Guajira', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1381 - RIONEGRO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6005 - RIONEGRO - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3360 - RIOSUCIO - Chocó', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1835 - RIOSUCIO - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1862 - RISARALDA - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3930 - RIVERA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6970 - ROLDANILLO - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6647 - RONCESVALLES - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2108 - ROSAS - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6660 - ROVIRA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6040 - SABANA DE TORRES - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1460 - SABANALARGA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1620 - SABANALARGA - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8648 - SABANALARGA - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4215 - SABANAS DE SAN ANGEL - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1567 - SABOYA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2770 - SAHAGUN - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3967 - SALADOBLANCO - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1830 - SALAMINA - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5152 - SALAZAR - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6650 - SALDAÑA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5450 - SALENTO - Quindio', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1568 - SAMACA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1853 - SAMANA - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4870 - SAMANIEGO - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6360 - SAMPUES - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3952 - SAN AGUSTIN - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2435 - SAN ALBERTO - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8103 - SAN ANDRES - Archipiélago de San Andrés, Providencia y Santa Catalina', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6068 - SAN ANDRES - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1462 - SAN ANDRES DE CUERQUIA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2775 - SAN ANDRES DE SOTAVENTO - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2777 - SAN ANTERO - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6652 - SAN ANTONIO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6362 - SAN BENITO ABAD - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3156 - SAN BERNARDO - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2757 - SAN BERNARDO DEL VIENTO - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1396 - SAN CARLOS - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2730 - SAN CARLOS - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4540 - SAN CARLOS DE GUAROA - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3157 - SAN CAYETANO - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1385 - SAN CRISTOBAL - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2440 - SAN DIEGO - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1260 - SAN ESTANISLAO - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3158 - SAN FRANCISCO - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6042 - SAN GIL - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1263 - SAN JACINTO - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1386 - SAN JERONIMO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1870 - SAN JOSÉ - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4872 - SAN JOSE DE ALBAN - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1466 - SAN JOSE DE LA MONTAÑA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1569 - SAN JOSE DE PARE - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8303 - SAN JOSE DEL GUAVIARE - Guaviare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4532 - SAN JUAN DE ARAMA - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1250 - SAN JUAN DE NEPOMUCENO - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3159 - SAN JUAN DE RIOSECO - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3640 - SAN JUAN DEL CESAR - La Guajira', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4542 - SAN JUANITO - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4874 - SAN LORENZO - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1345 - SAN LUIS - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6653 - SAN LUIS - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1570 - SAN LUIS DE GACENO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8650 - SAN LUIS DE PALENQUE - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6364 - SAN MARCOS - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4535 - SAN MARTIN - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1571 - SAN MATEO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7940 - SAN MIGUEL - Putumayo', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6366 - SAN ONOFRE - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4876 - SAN PABLO - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1255 - SAN PABLO - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1387 - SAN PEDRO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6368 - SAN PEDRO - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1391 - SAN PEDRO DE URABA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2772 - SAN PELAYO - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1470 - SAN RAFAEL - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1472 - SAN ROQUE - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4260 - SAN SEBASTIAN - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2165 - SAN SEBASTIAN - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1388 - SAN VICENTE - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6022 - SAN VICENTE DE CHUCURI - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7565 - SAN VICENTE DEL CAGUAN - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4810 - SANDONA - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4263 - SANTA ANA - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4878 - SANTA BARBARA DE ISCUANDE - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1267 - SANTA CATALINA - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6654 - SANTA ISABEL - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3950 - SANTA MARIA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4210 - SANTA MARTA - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5715 - SANTA ROSA DE CABAL - Risaralda', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1340 - SANTA ROSA DE OSOS - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1573 - SANTA ROSA DE VITERBO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1270 - SANTA ROSA DEL SUR - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8520 - SANTA ROSALIA - Vichada', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1574 - SANTA SOFIA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1389 - SANTAFE DE ANTIOQUIA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1572 - SANTANA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6920 - SANTANDER DE QUILICHAO - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1474 - SANTO DOMINGO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1660 - SANTO TOMAS - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1390 - SANTUARIO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7360 - SARAVENA - Arauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5150 - SARDINATA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3167 - SASAIMA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1575 - SATIVANORTE - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1476 - SEGOVIA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6950 - SEVILLA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7901 - SIBUNDOY - Putumayo', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5164 - SILOS - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3163 - SILVANIA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6916 - SILVIA - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6072 - SIMACOTA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3165 - SIMIJACA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1265 - SIMITI - Bolívar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6370 - SINCE - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6303 - SINCELEJO - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1576 - SOATA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1578 - SOCHA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6044 - SOCORRO - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1577 - SOCOTA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1516 - SOGAMOSO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7567 - SOLANO - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1204 - SOLEDAD - Atlántico', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3904 - SOLITA - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1579 - SOMONDOCO - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1346 - SONSON - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1397 - SOPETRAN - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('960 - SOPO - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1580 - SOTAQUIRA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4862 - SOTOMAYOR - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2111 - SUAREZ - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6657 - SUAREZ - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3973 - SUAZA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('980 - SUBACHOQUE - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6372 - SUCRE - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6076 - SUCRE - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3160 - SUESCA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3161 - SUPATA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6077 - SURATA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3168 - SUSA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1582 - SUSACON - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1583 - SUTAMARCHAN - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3375 - TADO - Chocó', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2470 - TAMALAMEQUE - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8660 - TAMARA - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7370 - TAME - Arauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1357 - TAMESIS - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4880 - TAMINANGO - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1478 - TARAZA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3955 - TARQUI - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1480 - TARSO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8663 - TAURAMENA - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3960 - TELLO - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3101 - TENA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('940 - TENJO - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1584 - TENZA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5172 - TEORAMA - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3957 - TERUEL - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3970 - TESALIA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1585 - TIBANA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5170 - TIBU - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2780 - TIERRALTA - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3965 - TIMANA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6917 - TIMBIO - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2180 - TIMBIQUI - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1586 - TIPACOQUE - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1392 - TITIRIBI - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1587 - TOCA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1588 - TOGUI - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1482 - TOLEDO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5160 - TOLEDO - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6380 - TOLU - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6382 - TOLUVIEJO - Sucre', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6078 - TONA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3172 - TOPAIPI - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2175 - TORIBIO - CAUCA', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6974 - TORO - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2107 - TOTORO - Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8665 - TRINIDAD - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6952 - TRUJILLO - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6955 - TULUA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4882 - TUMACO - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1503 - TUNJA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4808 - TUQUERRES - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1332 - TURBO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1589 - TURMEQUE - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1590 - TUTA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3174 - UBALA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('290 - UBATE - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6982 - ULLOA - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1592 - UMBITA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('730 - UNE - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3370 - UNGUIA - Chocó', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1395 - URRAO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3660 - URUMITA - La Guajira', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3176 - UTICA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1484 - VALDIVIA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2786 - VALENCIA - Córdoba', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6680 - VALLE DE SAN JUAN - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2403 - VALLEDUPAR - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2410 - VALLEDUPAR - CDV - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1486 - VALPARAISO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7580 - VALPARAISO - Caquetá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1456 - VEGACHI - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6046 - VELEZ - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6670 - VENADILLO - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3150 - VENECIA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1593 - VENTAQUEMADA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3178 - VERGARA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6079 - VETAS - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1865 - VICTORIA - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6910 - VIJES - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1546 - VILLA DE LEYVA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('5180 - VILLACARO - Norte de Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('7950 - VILLAGARZON - Putumayo', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3105 - VILLAGOMEZ - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6628 - VILLAHERMOSA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8640 - VILLANUEVA - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6081 - VILLANUEVA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3180 - VILLAPINZON - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6632 - VILLARRICA - Tolima', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4501 - VILLAVICENCIO - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3980 - VILLAVIEJA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3121 - VILLETA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3186 - VIOTA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4550 - VISTAHERMOSA - Meta', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1855 - VITERBO - Caldas', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3190 - YACOPI - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('4822 - YACUANQUER - Nariño', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3940 - YAGUARA - Huila', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1398 - YARUMAL - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1394 - YONDO - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('8603 - YOPAL - Casanare', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6048 - ZAPATOCA - Santander', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1399 - ZARAGOZA(Operando desde la oficina de Caucasia-Antioquia) - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('6972 - ZARZAL - Valle del Cauca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1595 - ZETAQUIRA - Boyacá', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('970 - ZIPAQUIRA - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1205 - ZONA BANANERA - Magdalena', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3123 - GUAYABETAL - Cundinamarca', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1415 - AMALFI - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1356 - SAN JUAN DE URABA - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('2445 - PUEBLO BELLO - Cesar', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('1487 - ENTRERRIOS - Antioquia', 'BANK_BRANCH', true);
INSERT INTO lists (name, list, active) VALUES ('3655 - VILLANUEVA - La Guajira', 'BANK_BRANCH', true);