insert into config_values (name, value, created_at, updated_at) values ('full_budget', 80000000000, now(), now());
insert into config_values (name, value, created_at, updated_at) values ('partial_budget', 80000000000, now(), now());
insert into config_values (name, value, created_at, updated_at) values ('budget_Sector Agrícola', 0.7, now(), now());
insert into config_values (name, value, created_at, updated_at) values ('budget_Sector Pecuario', 0.3, now(), now());
insert into config_values (name, value, created_at, updated_at) values ('minimun_hectarea_range', 0.5, now(), now());
insert into config_values (name, value, created_at, updated_at) values ('maximun_hectarea_range', 5, now(), now());
insert into config_values (name, value, created_at, updated_at) values ('percentage_to_subsidize', 0.2, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_AMAZONAS', 0.000363, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_ANTIOQUIA', 0.144598, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_ARAUCA', 0.017545, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_ATLANTICO', 0.013910, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_BOLIVAR', 0.030869, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_BOYACA', 0.069695, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_CALDAS', 0.015294, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_CAQUETA', 0.007484, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_CASANARE', 0.017461, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_CAUCA', 0.023120, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_CESAR', 0.020569, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_CHOCO', 0.008653, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_CORDOBA', 0.037445, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_CUNDINAMARCA', 0.158626, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_GUAINIA', 0.000466, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_GUAVIARE', 0.001739, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_HUILA', 0.039401, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_LA GUAJIRA', 0.025826, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_MAGDALENA', 0.033080, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_META', 0.045076, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_NARIÑO', 0.040592, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_NORTE DE SANTANDER', 0.025273, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_PUTUMAYO', 0.003205, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_QUINDIO', 0.015446, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_RISARALDA', 0.012154, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_SAN ANDRES Y PROVIDENCIA', 0.000010, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_SANTANDER', 0.079130, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_SUCRE', 0.013941, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_TOLIMA', 0.051624, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_VALLE DEL CAUCA', 0.046618, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_VAUPES', 0.000280, now(), now());
insert into config_values (name, value, created_at, updated_at) VALUES ('perc_VICHADA', 0.000509, now(), now());

insert into lists (name, list, active) VALUES ('Sector Agrícola', 'CHAIN', TRUE);
insert into lists (name, list, active) VALUES ('Sector Pecuario', 'CHAIN', TRUE);
insert into lists (name, list, active) VALUES ('Agrícola', 'CROP_GROUP_Sector Agrícola', TRUE);
insert into lists (name, list, active) VALUES ('Acuícola', 'CROP_GROUP_Sector Pecuario', TRUE);
insert into lists (name, list, active) VALUES ('Avícola', 'CROP_GROUP_Sector Pecuario', TRUE);
insert into lists (name, list, active) VALUES ('Porcícola', 'CROP_GROUP_Sector Pecuario', TRUE);
insert into lists (name, list, active) VALUES ('Ovino Caprino', 'CROP_GROUP_Sector Pecuario', TRUE);
insert into lists (name, list, active) VALUES ('Bobino', 'CROP_GROUP_Sector Pecuario', TRUE);

insert into lists (name, list, active) VALUES ('lts', 'MEASUREMENT_UNIT', TRUE);
insert into lists (name, list, active) VALUES ('ml', 'MEASUREMENT_UNIT', TRUE);
insert into lists (name, list, active) VALUES ('cm3', 'MEASUREMENT_UNIT', TRUE);
insert into lists (name, list, active) VALUES ('kg', 'MEASUREMENT_UNIT', TRUE);
insert into lists (name, list, active) VALUES ('mg', 'MEASUREMENT_UNIT', TRUE);
insert into lists (name, list, active) VALUES ('lbs', 'MEASUREMENT_UNIT', TRUE);
insert into lists (name, list, active) VALUES ('oz', 'MEASUREMENT_UNIT', TRUE);

insert into lists (name, list, active) VALUES ('Caja', 'PRESENTATION', TRUE);
insert into lists (name, list, active) VALUES ('Tetrapack', 'PRESENTATION', TRUE);
insert into lists (name, list, active) VALUES ('Embase Plático', 'PRESENTATION', TRUE);

insert into lists (name, list, active) VALUES ('Agrario de Colombia', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Av Villas', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('BBVA', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Bogotá', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Citibank', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Coopcentral', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Davivienda', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Occidente', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Falabella', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Finandina', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('GNB Sudameris', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Itaú Corbanca', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Mundo Mujer', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Pichincha', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Popular', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Credifinanciera', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Santander', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Serfinanzas', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Bancoldex', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Bancolombia', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('Bancomeva', 'BANK', TRUE);
insert into lists (name, list, active) VALUES ('BNP Paribas', 'BANK', TRUE);

insert into lists (name, list, active) VALUES ('Sucursal Norte', 'BANK_BRANCH', TRUE);
insert into lists (name, list, active) VALUES ('Sucursal Sur', 'BANK_BRANCH', TRUE);
insert into lists (name, list, active) VALUES ('Sucursal Este', 'BANK_BRANCH', TRUE);
insert into lists (name, list, active) VALUES ('Sucursal Oeste', 'BANK_BRANCH', TRUE);

insert into lists (name, list, active) VALUES ('Ahorros', 'BANK_ACCOUNT_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Corriente', 'BANK_ACCOUNT_TYPE', TRUE);

insert into lists (name, list, active) VALUES ('Pago en sucursal', 'PAYMENT_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Pago por correo', 'PAYMENT_TYPE', TRUE);

insert into lists (name, list, active) VALUES ('Documento incompleto', 'REJECT_REASON', TRUE);
insert into lists (name, list, active) VALUES ('Documento ilegible', 'REJECT_REASON', TRUE);
insert into lists (name, list, active) VALUES ('Otros', 'REJECT_REASON', TRUE);

insert into lists (name, list, active) VALUES ('Factura de Compra', 'FILE_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('RUT', 'FILE_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Documento de Identidad', 'FILE_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Certificado de Pequeño Productor', 'FILE_TYPE', TRUE);

insert into lists (name, list, active) VALUES ('Cédula de Ciudadanía', 'DOC_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Cédula de Extranjería', 'DOC_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Pasaporte', 'DOC_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('NUIP', 'DOC_TYPE', TRUE);

insert into lists (name, list, active) VALUES ('Masculino', 'GENDER', TRUE);
insert into lists (name, list, active) VALUES ('Femenino', 'GENDER', TRUE);
insert into lists (name, list, active) VALUES ('Otro', 'GENDER', TRUE);

insert into lists (name, list, active) VALUES ('Hombre', 'SEX', TRUE);
insert into lists (name, list, active) VALUES ('Mujer', 'SEX', TRUE);
insert into lists (name, list, active) VALUES ('No Binario', 'SEX', TRUE);

insert into lists (name, list, active) VALUES ('Cuidadores', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Personas en actividades sexuales pagadas', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Reciclador/Corotero', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Vendedores ambulantes', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Artistas', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Habitante de Calle', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Cabezas de familia', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Reintegrado', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Sectores LGTBI', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Víctima del conflicto armado', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Migrante Venezolano', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Otros migrantes', 'POPULATION_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Ninguno de los anteriores', 'POPULATION_GROUPS', TRUE);

insert into lists (name, list, active) VALUES ('Indígena', 'ETHNIC_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Gitano-Rrom', 'ETHNIC_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Raizal', 'ETHNIC_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Palenquero', 'ETHNIC_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Afrocolombiano', 'ETHNIC_GROUPS', TRUE);
insert into lists (name, list, active) VALUES ('Ninguno de los anteriores', 'ETHNIC_GROUPS', TRUE);

insert into lists (name, list, active) VALUES ('Auditiva', 'TYPE_DISABILITY', TRUE);
insert into lists (name, list, active) VALUES ('Cognitiva', 'TYPE_DISABILITY', TRUE);
insert into lists (name, list, active) VALUES ('Física', 'TYPE_DISABILITY', TRUE);
insert into lists (name, list, active) VALUES ('Múltiple', 'TYPE_DISABILITY', TRUE);
insert into lists (name, list, active) VALUES ('Psicosocial', 'TYPE_DISABILITY', TRUE);
insert into lists (name, list, active) VALUES ('Sordo-Ceguera', 'TYPE_DISABILITY', TRUE);
insert into lists (name, list, active) VALUES ('No presenta Discapacidad', 'TYPE_DISABILITY', TRUE);

insert into lists (name, list, active) VALUES ('Organización 1', 'ORGANIZATION_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Organización 2', 'ORGANIZATION_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Organización 3', 'ORGANIZATION_TYPE', TRUE);

insert into lists (name, list, active) VALUES ('Documento incompleto', 'PEOPLE_REJECT_REASON', TRUE);
insert into lists (name, list, active) VALUES ('Beneficiario no cumple', 'PEOPLE_REJECT_REASON', TRUE);
insert into lists (name, list, active) VALUES ('Documento ilegible', 'PEOPLE_REJECT_REASON', TRUE);
insert into lists (name, list, active) VALUES ('Otros', 'PEOPLE_REJECT_REASON', TRUE);
insert into lists (name, list, active) VALUES ('Documento incompleto', 'COMPANY_REJECT_REASON', TRUE);
insert into lists (name, list, active) VALUES ('Documento ilegible', 'COMPANY_REJECT_REASON', TRUE);
insert into lists (name, list, active) VALUES ('Otros', 'COMPANY_REJECT_REASON', TRUE);
insert into lists (name, list, active) VALUES ('Documento de Identificación', 'PEOPLE_DOCUMENTS', TRUE);
insert into lists (name, list, active) VALUES ('Declaración Juramentada', 'PEOPLE_DOCUMENTS', TRUE);
insert into lists (name, list, active) VALUES ('Formato de Inscripción', 'PEOPLE_DOCUMENTS', TRUE);
insert into lists (name, list, active) VALUES ('Contrato o Certificación Laboral ', 'PEOPLE_DOCUMENTS', TRUE);
insert into lists (name, list, active) VALUES ('Copia certificado de aportes a Seguridad Social Mes 1', 'PEOPLE_DOCUMENTS', TRUE);
insert into lists (name, list, active) VALUES ('Comprobante De Nómina Mes 1', 'PEOPLE_DOCUMENTS', TRUE);
insert into lists (name, list, active) VALUES ('Copia certificado de aportes a Seguridad Social Mes 2', 'PEOPLE_DOCUMENTS', TRUE);
insert into lists (name, list, active) VALUES ('Comprobante De Nómina Mes 2', 'PEOPLE_DOCUMENTS', TRUE);
insert into lists (name, list, active) VALUES ('Copia certificado de aportes a Seguridad Social Mes 3', 'PEOPLE_DOCUMENTS', TRUE);
insert into lists (name, list, active) VALUES ('Comprobante De Nómina Mes 3', 'PEOPLE_DOCUMENTS', TRUE);
insert into lists (name, list, active) VALUES ('Indefinido ', 'CONTRACT_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Termino Fijo', 'CONTRACT_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Jul-21', 'MONTH_SUBSIDY', TRUE);
insert into lists (name, list, active) VALUES ('Ago-21', 'MONTH_SUBSIDY', TRUE);
insert into lists (name, list, active) VALUES ('Sep-21', 'MONTH_SUBSIDY', TRUE);
insert into lists (name, list, active) VALUES ('Oct-21', 'MONTH_SUBSIDY', TRUE);
insert into lists (name, list, active) VALUES ('Nov-21', 'MONTH_SUBSIDY', TRUE);
insert into lists (name, list, active) VALUES ('Dic-21', 'MONTH_SUBSIDY', TRUE);
insert into lists (name, list, active) VALUES ('Ene-22', 'MONTH_SUBSIDY', TRUE);
insert into lists (name, list, active) VALUES ('Feb-22', 'MONTH_SUBSIDY', TRUE);
insert into lists (name, list, active) VALUES ('Mar-22', 'MONTH_SUBSIDY', TRUE);
insert into lists (name, list, active) VALUES ('Abr-22', 'MONTH_SUBSIDY', TRUE);
insert into lists (name, list, active) VALUES ('May-22', 'MONTH_SUBSIDY', TRUE);
insert into lists (name, list, active) VALUES ('Riesgo I', 'ARL_LEVEL', TRUE);
insert into lists (name, list, active) VALUES ('Riesgo II', 'ARL_LEVEL', TRUE);
insert into lists (name, list, active) VALUES ('Riesgo III', 'ARL_LEVEL', TRUE);
insert into lists (name, list, active) VALUES ('Riesgo IV', 'ARL_LEVEL', TRUE);
insert into lists (name, list, active) VALUES ('Riesgo V', 'ARL_LEVEL', TRUE);
insert into lists (name, list, active) VALUES ('Agremiaciones / Comunidad Religiosa', 'COMPANY_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Mutuales', 'COMPANY_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Cooperativa Trabajo Asociado', 'COMPANY_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Entidad Educativa', 'COMPANY_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Institución Prestadora de Salud', 'COMPANY_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Otra', 'COMPANY_TYPE', TRUE);
insert into lists (name, list, active) VALUES ('Usaquén', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Suba', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Chapinero', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Santa Fe', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('San Cristóbal', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Usme', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Tunjuelito', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Bosa', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Kennedy', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Fontibón', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Engativá', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Barrios Unidos', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Teusaquillo', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Los Mártires', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Antonio Nariño', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Puente Aranda', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('La Candelaria', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Rafael Uribe Uribe', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Ciudad Bolívar', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Sumapaz', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('No aplica', 'LOCALITY', TRUE);
insert into lists (name, list, active) VALUES ('Micro empresa', 'COMPANY_SIZE', TRUE);
insert into lists (name, list, active) VALUES ('Pequeña Empresa', 'COMPANY_SIZE', TRUE);
insert into lists (name, list, active) VALUES ('Mediana Empresa ', 'COMPANY_SIZE', TRUE);
insert into lists (name, list, active) VALUES ('Gran Empresa', 'COMPANY_SIZE', TRUE);
insert into lists (name, list, active) VALUES ('Colsubsidio', 'CCF', TRUE);
insert into lists (name, list, active) VALUES ('Cafam', 'CCF', TRUE);
insert into lists (name, list, active) VALUES ('Compensar', 'CCF', TRUE);
insert into lists (name, list, active) VALUES ('Comfacundi', 'CCF', TRUE);
