--Insert new supply
INSERT INTO supplies (name, price, crop_group_id, active, created_at, updated_at) VALUES
('Compuesto 10-30-10*', 20993, 3, TRUE, now(), now());

UPDATE supplies set price = 5021 where name = 'Simple 18-46-0 (DAP)';
UPDATE supplies set price = 4901 where name = 'Simple 46-0-0 (Urea)';
UPDATE supplies set price = 4669 where name = 'Compuesto 18-18-18';
UPDATE supplies set price = 4801 where name = 'Simple 0-0-60 (KCL)';
UPDATE supplies set price = 4396 where name = 'Compuesto 15-15-15';
UPDATE supplies set price = 4684 where name = 'Compuesto 10-30-10';
UPDATE supplies set price = 4511 where name = 'Compuesto 10-20-20';
UPDATE supplies set price = 4269 where name = 'Compuesto 17-6-18-2';
UPDATE supplies set price = 4514 where name = 'Compuesto 13-26-6';
UPDATE supplies set price = 4283 where name = 'Compuesto 15-4-23';
UPDATE supplies set price = 4573 where name = 'Compuesto 13-26-10';
UPDATE supplies set price = 4703 where name = 'Compuesto 25-4-24';
UPDATE supplies set price = 4565 where name = 'Compuesto 12-24-12';
UPDATE supplies set price = 4206 where name = 'Compuesto 17-6-18-6';
UPDATE supplies set price = 4269 where name = 'Compuesto 17-6-18-3';
UPDATE supplies set price = 4532 where name = 'Compuesto 10-20-30';
UPDATE supplies set price = 4252 where name = 'Compuesto 10-20-23';
UPDATE supplies set price = 4600 where name = 'Compuesto 10-24-24';
UPDATE supplies set price = 4453 where name = 'Compuesto 19-4-19';
UPDATE supplies set price = 4615 where name = 'Compuesto 12-24-24';
UPDATE supplies set price = 5026.1 where name = 'Alimento balanceado para mojarra o tilapia iniciación';
UPDATE supplies set price = 3758.925 where name = 'Alimento balanceado para mojarra o tilapia levante';
UPDATE supplies set price = 3222.2 where name = 'Alimento balanceado para mojarra o tilapia finalización';
UPDATE supplies set price = 4693.75 where name = 'Alimento balanceado para trucha iniciación';
UPDATE supplies set price = 5608.3 where name = 'Alimento balanceado para trucha levante';
UPDATE supplies set price = 6168.55 where name = 'Alimento balanceado para trucha finalización';
UPDATE supplies set price = 2967.95 where name = 'Alimento balanceado para pollo iniciación';
UPDATE supplies set price = 2907.75 where name = 'Alimento balanceado para pollo engorde';
UPDATE supplies set price = 2479.775 where name = 'Alimento balanceado para ponedora levante';
UPDATE supplies set price = 2479.775 where name = 'Alimento balanceado para ponedora postura';
UPDATE supplies set price = 3512.1 where name = 'Alimento balanceado para iniciación';
UPDATE supplies set price = 2662.425 where name = 'Alimento balanceado para levante';
UPDATE supplies set price = 2412.25 where name = 'Alimento balanceado para engorde';
UPDATE supplies set price = 2440.425 where name = 'Alimento balanceado para gestación';
UPDATE supplies set price = 2663.55 where name = 'Alimento balanceado para lactancia' and crop_group_id = 6;
UPDATE supplies set price = 2100 where name = 'Alimento balanceado para levante y cría';
UPDATE supplies set price = 2100 where name = 'Alimento balanceado para ceba';
UPDATE supplies set price = 2472.25 where name = 'Alimento balanceado para lactancia' and crop_group_id = 7;
UPDATE supplies set price = 2173 where name = 'Alimento balanceado para novillas';
UPDATE supplies set price = 2526.9 where name = 'Alimento balanceado para terneros y terneras';
UPDATE supplies set price = 1787.5 where name = 'Alimento balanceado para suplementación alimenticia';
UPDATE supplies set price = 2526.9 where name = 'Alimento balanceado para crianza terneras';
UPDATE supplies set price = 2173 where name = 'Alimento balanceado para levante novillas';
UPDATE supplies set price = 1964.45 where name = 'Alimento balanceado para vacas de leche en producción';
UPDATE supplies set price = 1964.45 where name = 'Alimento balanceado para animales en producción de doble propósito';
