insert into lists (name, list, active) VALUES ('Antioquia', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Norte de Santander', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Meta', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Chocó', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Huila', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Bolívar', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Cundinamarca', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Cesar', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Santander', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Caldas', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Casanare', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Caquetá', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('La Guajira', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Valle del Cauca', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Nariño', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Magdalena', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Cauca', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Boyacá', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Tolima', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Risaralda', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Arauca', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Quindío', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Córdoba', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Atlántico', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('guainía', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Sucre', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Guaviare', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Vaupés', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Putumayo', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Vichada', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Amazonas', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('San Andrés y Providencia', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('Abejorral', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Ábrego', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Abriaquí', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Acacías', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Acandí', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Acevedo', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Achí', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Agrado', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Agua de Dios', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Aguachica', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Aguada', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Aguadas', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Aguazul', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Agustín Codazzi', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Aipe', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Albán', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Albania', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('Albania', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Albania', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Alcalá', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Aldana', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Alejandría', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Algarrobo', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Algeciras', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Almaguer', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Almeida', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Alpujarra', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Altamira', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Alto Baudó', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Altos del Rosario', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Alvarado', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Amagá', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Amalfi', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Ambalema', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Anapoima', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Ancuya', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Andalucía', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Andes', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Angelópolis', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Angostura', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Anolaima', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Anorí', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Anserma', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Ansermanuevo', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Anzá', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Anzoátegui', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Apartadó', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Apía', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Apulo', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Aquitania', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Aracataca', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Aranzazu', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Aratoca', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Arauca', 'Arauca', TRUE);
insert into lists (name, list, active) VALUES ('Arauquita', 'Arauca', TRUE);
insert into lists (name, list, active) VALUES ('Arbeláez', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Arboleda', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Arboledas', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Arboletes', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Arcabuco', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Arenal', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Argelia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Argelia', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Argelia', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Ariguaní', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Arjona', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Armenia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Armenia', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('Armero', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Arroyohondo', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Astrea', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Ataco', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Ayapel', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Bagadó', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Bahía Solano', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Bajo Baudó', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Balboa', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Balboa', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Baranoa', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Baraya', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Barbacoas', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Barbosa', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Barbosa', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Barichara', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Barranca de Upía', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Barrancabermeja', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Barrancas', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Barranco de Loba', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Barrancominas', 'guainía', TRUE);
insert into lists (name, list, active) VALUES ('Barranquilla', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Becerril', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Belalcázar', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Belén', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Belén', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Belén de Bajirá', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Belén de los Andaquíes', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('Belén de Umbría', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Bello', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Belmira', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Beltrán', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Berbeo', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Betania', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Betéitiva', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Betulia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Betulia', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Bituima', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Boavita', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Bochalema', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Bogotá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Bojacá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Bojayá', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Bolívar', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Bolívar', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Bolívar', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Bolívar', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Bosconia', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Boyacá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Brazuelo de Papayal', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Briceño', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Briceño', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Bucaramanga', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Bucarasica', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Buenaventura', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Buenavista', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Buenavista', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Buenavista', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('Buenavista', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Buenos Aires', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Buesaco', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Buga', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Bugalagrande', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Buriticá', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Busbanzá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Cabrera', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Cabrera', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Cabuyaro', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Cáceres', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Cachipay', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Cáchira', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Cácota', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Caicedo', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Caicedonia', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Caimito', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Cajamarca', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Cajibío', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Cajicá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Calamar', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Calamar', 'Guaviare', TRUE);
insert into lists (name, list, active) VALUES ('Calarcá', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('Caldas', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Caldas', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Caldono', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Cali', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('California', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Calima', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Caloto', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Campamento', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Campo de la Cruz', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Campoalegre', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Campohermoso', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Canalete', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Candelaria', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Candelaria', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Cantagallo', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Cantón de San Pablo', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Cañasgordas', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Caparrapí', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Capitanejo', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Cáqueza', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Caracolí', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Caramanta', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Carcasí', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Carepa', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Carmen de Apicalá', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Carmen de Carupa', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Carolina del Príncipe', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Cartagena de Indias', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Cartagena del Chairá', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('Cartago', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Carurú', 'Vaupés', TRUE);
insert into lists (name, list, active) VALUES ('Casabianca', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Castilla la Nueva', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Caucasia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Cepitá', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Cereté', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Cerinza', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Cerrito', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Cerro de San Antonio', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Cértegui', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Chachagüí', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Chaguaní', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Chalán', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Chámeza', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Chaparral', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Charalá', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Charta', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Chía', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Chibolo', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Chigorodó', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Chima', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Chimá', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Chimichagua', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Chinácota', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Chinavita', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Chinchiná', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Chinú', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Chipaque', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Chipatá', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Chiquinquirá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Chíquiza', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Chiriguaná', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Chiscas', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Chita', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Chitagá', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Chitaraque', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Chivatá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Chivor', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Choachí', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Chocontá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Cicuco', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Ciénaga', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Ciénaga de Oro', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Ciénega', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Cimitarra', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Circasia', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('Cisneros', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Clemencia', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Cocorná', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Coello', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Cogua', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Colombia', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Colón', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Colón', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('Colosó', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Cómbita', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Concepción', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Concepción', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Concordia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Concordia', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Condoto', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Confines', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Consacá', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Contadero', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Contratación', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Convención', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Copacabana', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Coper', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Córdoba', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Córdoba', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Córdoba', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('Corinto', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Coromoro', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Corozal', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Corrales', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Cota', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Cotorra', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Covarachía', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Coveñas', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Coyaima', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Cravo Norte', 'Arauca', TRUE);
insert into lists (name, list, active) VALUES ('Cuaspud', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Cubará', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Cubarral', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Cucaita', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Cucunubá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Cúcuta', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Cucutilla', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Cuítiva', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Cumaral', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Cumaribo', 'Vichada', TRUE);
insert into lists (name, list, active) VALUES ('Cumbal', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Cumbitara', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Cunday', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Curillo', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('Curití', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Curumaní', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Dabeiba', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Dagua', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Dibulla', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Distracción', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Dolores', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Donmatías', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Dosquebradas', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Duitama', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Duranía', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Ebéjico', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('El Águila', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('El Atrato', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('El Bagre', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('El Banco', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('El Cairo', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('El Calvario', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('El Carmen', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('El Carmen de Atrato', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('El Carmen de Bolívar', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('El Carmen de Chucurí', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('El Carmen de Viboral', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('El Carmen del Darién', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('El Castillo', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('El Cerrito', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('El Charco', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('El Cocuy', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('El Colegio', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('El Copey', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('El Doncello', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('El Dorado', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('El Dovio', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('El Espinal', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('El Espino', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('El Guacamayo', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('El Guamo', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('El Molino', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('El Paso', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('El Paujil', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('El Peñol', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('El Peñol', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('El Peñón', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('El Peñón', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('El Peñón', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('El Piñón', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('El Pital', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('El Playón', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('El Retén', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('El Retiro', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('El Retorno', 'Guaviare', TRUE);
insert into lists (name, list, active) VALUES ('El Roble', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('El Rosal', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('El Rosario', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('El Santuario', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('El Socorro', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('El Tablón', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('El Tambo', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('El Tambo', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('El Tarra', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('El Zulia', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Elías', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Encino', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Entrerríos', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Envigado', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Facatativá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Falán', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Filadelfia', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Filandia', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('Firavitoba', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Flandes', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Florencia', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Florencia', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('Floresta', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Florián', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Florida', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Floridablanca', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Fómeque', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Fonseca', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Fortul', 'Arauca', TRUE);
insert into lists (name, list, active) VALUES ('Fosca', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Francisco Pizarro', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Fredonia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Fresno', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Frontino', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Fuente de Oro', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Fundación', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Funes', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Funza', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Fúquene', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Fusagasugá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Gachalá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Gachancipá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Gachantivá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Gachetá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Galán', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Galapa', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Galeras', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Gama', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Gamarra', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Gámbita', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Gámeza', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Garagoa', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Garzón', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Génova', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('Gigante', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Ginebra', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Giraldo', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Girardot', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Girardota', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Girón', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Gómez Plata', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('González', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Gramalote', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Granada', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Granada', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Granada', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Guaca', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Guacamayas', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Guacarí', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Guachené', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Guachetá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Guachucal', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Guadalupe', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Guadalupe', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Guadalupe', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Guaduas', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Guaitarilla', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Gualmatán', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Guamal', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Guamal', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Guamo', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Guapí', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Guapotá', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Guaranda', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Guarne', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Guasca', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Guatapé', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Guataquí', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Guatavita', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Guateque', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Guática', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Guavatá', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Guayabal de Síquima', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Guayabetal', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Guayatá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Güepsa', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Güicán', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Gutiérrez', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Hacarí', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Hatillo de Loba', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Hato Corozal', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Hato', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Hatonuevo', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Heliconia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Herrán', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Herveo', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Hispania', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Hobo', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Honda', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Ibagué', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Icononzo', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Iles', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Imués', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Inírida', 'Guainía', TRUE);
insert into lists (name, list, active) VALUES ('Inzá', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Ipiales', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Íquira', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Isnos', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Itagüí', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Istmina', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Ituango', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Iza', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Jambaló', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Jamundí', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Jardín', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Jenesano', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Jericó', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Jericó', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Jerusalén', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Jesús María', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Jordán', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Juan de Acosta', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Junín', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Juradó', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('La Apartada', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('La Argentina', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('La Belleza', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('La Calera', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('La Capilla', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('La Ceja', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('La Celia', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('La Cruz', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('La Cumbre', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('La Dorada', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('La Esperanza', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('La Estrella', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('La Florida', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('La Gloria', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('La Jagua de Ibirico', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('La Jagua del Pilar', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('La Llanada', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('La Macarena', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('La Merced', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('La Mesa', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('La Montañita', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('La Palma', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('La Paz', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('La Paz', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('La Peña', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('La Pintada', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('La Plata', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('La Playa de Belén', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('La Primavera', 'Vichada', TRUE);
insert into lists (name, list, active) VALUES ('La Salina', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('La Sierra', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('La Tebaida', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('La Tola', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('La Unión', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('La Unión', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('La Unión', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('La Unión', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('La Uribe', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('La Uvita', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('La Vega', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('La Vega', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('La Victoria', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('La Victoria', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('La Virginia', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Labateca', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Labranzagrande', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Landázuri', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Lebrija', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Leiva', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Lejanías', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Lenguazaque', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Lérida', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Leticia', 'Amazonas', TRUE);
insert into lists (name, list, active) VALUES ('Líbano', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Liborina', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Linares', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Litoral de San Juan', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Lloró', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('López de Micay', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Lorica', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Los Andes', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Los Córdobas', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Los Palmitos', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Los Patios', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Los Santos', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Lourdes', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Luruaco', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Macanal', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Macaravita', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Maceo', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Machetá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Madrid', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Magangué', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Magüí Payán', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Mahates', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Maicao', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Majagual', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Málaga', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Malambo', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Mallama', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Manatí', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Manaure Balcón del Cesar', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Manaure', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Maní', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Manizales', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Manta', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Manzanares', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Mapiripán', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Margarita', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('María la Baja', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Marinilla', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Maripí', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Mariquita', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Marmato', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Marquetalia', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Marsella', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Marulanda', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Matanza', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Medellín', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Medina', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Medio Atrato', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Medio Baudó', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Medio San Juan', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Melgar', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Mercaderes', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Mesetas', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Miraflores', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Miraflores', 'Guaviare', TRUE);
insert into lists (name, list, active) VALUES ('Miranda', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Mistrató', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Mitú', 'Vaupés', TRUE);
insert into lists (name, list, active) VALUES ('Mocoa', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('Mogotes', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Molagavita', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Momil', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Mompós', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Mongua', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Monguí', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Moniquirá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Montebello', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Montecristo', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Montelíbano', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Montenegro', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('Montería', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Monterrey', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Moñitos', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Morales', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Morales', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Morelia', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('Morroa', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Mosquera', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Mosquera', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Motavita', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Murillo', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Murindó', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Mutatá', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Mutiscua', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Muzo', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Nariño', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Nariño', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Nariño', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Nátaga', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Natagaima', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Nechí', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Necoclí', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Neira', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Neiva', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Nemocón', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Nilo', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Nimaima', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Nobsa', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Nocaima', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Norcasia', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Norosí', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Nóvita', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Nueva Granada', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Nuevo Colón', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Nunchía', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Nuquí', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Obando', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Ocamonte', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Ocaña', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Oiba', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Oicatá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Olaya', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Olaya Herrera', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Onzaga', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Oporapa', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Orito', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('Orocué', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Ortega', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Ospina', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Otanche', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Ovejas', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Pachavita', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Pacho', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Pácora', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Padilla', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Páez', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Páez', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Paicol', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Pailitas', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Paime', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Paipa', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Pajarito', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Palermo', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Palestina', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Palestina', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Palmar de Varela', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Palmar', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Palmas del Socorro', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Palmira', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Palocabildo', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Pamplona', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Pamplonita', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Pandi', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Panqueba', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Páramo', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Paratebueno', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Pasca', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Pasto', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Patía', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Pauna', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Paya', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Paz de Ariporo', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Paz del Río', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Pedraza', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Pelaya', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Pensilvania', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Peque', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Pereira', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Pesca', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Piamonte', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Piedecuesta', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Piedras', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Piendamó', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Pijao', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('Pijiño del Carmen', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Pinchote', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Pinillos', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Piojó', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Pisba', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Pitalito', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Pivijay', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Planadas', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Planeta Rica', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Plato', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Policarpa', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Polonuevo', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Ponedera', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Popayán', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Pore', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Potosí', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Pradera', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Prado', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Providencia', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Providencia y Santa Catalina Islas', 'San Andrés y Providencia', TRUE);
insert into lists (name, list, active) VALUES ('Pueblo Viejo', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Pueblo Bello', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Pueblo Nuevo', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Pueblo Rico', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Pueblorrico', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Puente Nacional', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Puerres', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Asís', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Berrío', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Boyacá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Caicedo', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Carreño', 'Vichada', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Colombia', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Concordia', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Escondido', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Gaitán', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Guzmán', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Leguízamo', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Libertador', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Lleras', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Puerto López', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Milán', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Nare', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Nariño', 'Amazonas', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Parra', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Rico', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Rico', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Rondón', 'Arauca', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Salgar', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Santander', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Tejada', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Triunfo', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Puerto Wilches', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Pulí', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Pupiales', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Puracé', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Purificación', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Purísima', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Quebradanegra', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Quetame', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Quibdó', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Quimbaya', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('Quinchía', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Quípama', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Quipile', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Ragonvalia', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Ramiriquí', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Ráquira', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Recetor', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Regidor', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Remedios', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Remolino', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Repelón', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Restrepo', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Restrepo', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Ricaurte', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Ricaurte', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Río de Oro', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Río Iró', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Río Quito', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Río Viejo', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Rioblanco', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Riofrío', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Riohacha', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Rionegro', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Rionegro', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Riosucio', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Riosucio', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Risaralda', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Rivera', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Roberto Payán', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Roldanillo', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Roncesvalles', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Rondón', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Rosas', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Rovira', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Sabana de Torres', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Sabanas de San Ángel', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Sabanagrande', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Sabanalarga', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Sabanalarga', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Sabanalarga', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Sabaneta', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Saboyá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Sácama', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Sáchica', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Sahagún', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Saladoblanco', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Salamina', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Salamina', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Salazar de Las Palmas', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Saldaña', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Salento', 'Quindío', TRUE);
insert into lists (name, list, active) VALUES ('Salgar', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Samacá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Samaná', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Samaniego', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Sampués', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('San Agustín', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('San Alberto', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('San Andrés', 'San Andrés y Providencia', TRUE);
insert into lists (name, list, active) VALUES ('San Andrés', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('San Andrés de Cuerquia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San Andrés de Sotavento', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('San Antero', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('San Antonio', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('San Antonio de Palmito', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('San Antonio del Tequendama', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('San Benito', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('San Benito Abad', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('San Bernardo', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('San Bernardo', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('San Bernardo del Viento', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('San Calixto', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('San Carlos', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San Carlos', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('San Carlos de Guaroa', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('San Cayetano', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('San Cayetano', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('San Cristóbal', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('San Diego', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('San Eduardo', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('San Estanislao', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('San Fernando', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('San Francisco', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San Francisco', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('San Francisco', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('San Gil', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('San Jacinto', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('San Jacinto del Cauca', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('San Jerónimo', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San Joaquín', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('San José', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('San José de Albán', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('San José de Miranda', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('San José de Pare', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('San José de Uré', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('San José de la Montaña', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San José del Fragua', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('San José del Guaviare', 'Guaviare', TRUE);
insert into lists (name, list, active) VALUES ('San José del Palmar', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('San Juan de Arama', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('San Juan de Betulia', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('San Juan de Rioseco', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('San Juan de Urabá', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San Juan del Cesar', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('San Juan Nepomuceno', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('San Juanito', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('San Lorenzo', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('San Luis', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San Luis', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('San Luis de Gaceno', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('San Luis de Palenque', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('San Marcos', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('San Martín', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('San Martín', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('San Martín de Loba', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('San Mateo', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('San Miguel', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('San Miguel', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('San Miguel de Sema', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('San Onofre', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('San Pablo', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('San Pablo', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('San Pablo de Borbur', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('San Pedro', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('San Pedro', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('San Pedro de Cartago', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('San Pedro de Urabá', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San Pedro de los Milagros', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San Pelayo', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('San Rafael', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San Roque', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San Sebastián', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('San Sebastián de Buenavista', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('San Vicente', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('San Vicente de Chucurí', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('San Vicente del Caguán', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('San Zenón', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Sandoná', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Santa Ana', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Santa Bárbara', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Santa Bárbara', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Santa Bárbara', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Santa Bárbara de Pinto', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Santa Catalina', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Santa Fe de Antioquia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Santa Helena del Opón', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Santa Isabel', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Santa Lucía', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Santa María', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Santa María', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Santa Marta', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Santa Rosa', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Santa Rosa', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Santa Rosa de Cabal', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Santa Rosa de Osos', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Santa Rosa de Viterbo', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Santa Rosa del Sur', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Santa Rosalía', 'Vichada', TRUE);
insert into lists (name, list, active) VALUES ('Santa Sofía', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Santacruz', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Santana', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Santander de Quilichao', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Santiago', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Santiago', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('Santo Domingo', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Santo Domingo de Silos', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Santo Tomás', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Santuario', 'Risaralda', TRUE);
insert into lists (name, list, active) VALUES ('Sapuyes', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Saravena', 'Arauca', TRUE);
insert into lists (name, list, active) VALUES ('Sardinata', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Sasaima', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Sativanorte', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Sativasur', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Segovia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Sesquilé', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Sevilla', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Siachoque', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Sibaté', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Sibundoy', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('Silvania', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Silvia', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Simacota', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Simijaca', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Simití', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Sincé', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Sincelejo', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Sipí', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Sitionuevo', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Soacha', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Soatá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Socha', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Socotá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Sogamoso', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Solano', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('Soledad', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Solita', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('Somondoco', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Sonsón', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Sopetrán', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Soplaviento', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Sopó', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Sora', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Soracá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Sotaquirá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Sotará', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Suaita', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Suán', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Suárez', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Suárez', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Suaza', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Subachoque', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Sucre', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Sucre', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Sucre', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Suesca', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Supatá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Supía', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Suratá', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Susa', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Susacón', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Sutamarchán', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Sutatausa', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Sutatenza', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Tabio', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Tadó', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Talaigua Nuevo', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Tamalameque', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Támara', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Tame', 'Arauca', TRUE);
insert into lists (name, list, active) VALUES ('Támesis', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Taminango', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Tangua', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Taraira', 'Vaupés', TRUE);
insert into lists (name, list, active) VALUES ('Tarazá', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Tarquí', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Tarso', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Tasco', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Tauramena', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Tausa', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Tello', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Tena', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Tenerife', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Tenjo', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Tenza', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Teorama', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Teruel', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Tesalia', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Tibacuy', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Tibaná', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Tibasosa', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Tibirita', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Tibú', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Tierralta', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Timaná', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Timbío', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Timbiquí', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Tinjacá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Tipacoque', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Tiquisio', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Titiribí', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Toca', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Tocaima', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Tocancipá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Togüí', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Toledo', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Toledo', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Tolú', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Tolú Viejo', 'Sucre', TRUE);
insert into lists (name, list, active) VALUES ('Tona', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Tópaga', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Topaipí', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Toribío', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Toro', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Tota', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Totoró', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Trinidad', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Trujillo', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Tubará', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Tuchín', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Tuluá', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Tumaco', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Tunja', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Tununguá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Túquerres', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Turbaco', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Turbaná', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Turbo', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Turmequé', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Tuta', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Tutazá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Ubalá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Ubaque', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Ubaté', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Ulloa', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Úmbita', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Une', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Unión Panamericana', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Unguía', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Uramita', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Uribia', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Urrao', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Urumita', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Usiacurí', 'Atlántico', TRUE);
insert into lists (name, list, active) VALUES ('Útica', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Valdivia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Valencia', 'Córdoba', TRUE);
insert into lists (name, list, active) VALUES ('Valle de San José', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Valle de San Juan', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Valle del Guamuez', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('Valledupar', 'Cesar', TRUE);
insert into lists (name, list, active) VALUES ('Valparaíso', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Valparaíso', 'Caquetá', TRUE);
insert into lists (name, list, active) VALUES ('Vegachí', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Vélez', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Venadillo', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Venecia', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Venecia', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Ventaquemada', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Vergara', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Versalles', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Vetas', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Vianí', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Victoria', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Vigía del Fuerte', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Vijes', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Villa Caro', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Villa de Leyva', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Villa del Rosario', 'Norte de Santander', TRUE);
insert into lists (name, list, active) VALUES ('Villa Rica', 'Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Villagarzón', 'Putumayo', TRUE);
insert into lists (name, list, active) VALUES ('Villagómez', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Villahermosa', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Villamaría', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Villanueva', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Villanueva', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Villanueva', 'La Guajira', TRUE);
insert into lists (name, list, active) VALUES ('Villanueva', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Villapinzón', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Villarrica', 'Tolima', TRUE);
insert into lists (name, list, active) VALUES ('Villavicencio', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Villavieja', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Villeta', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Viotá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Viracachá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Vista Hermosa', 'Meta', TRUE);
insert into lists (name, list, active) VALUES ('Viterbo', 'Caldas', TRUE);
insert into lists (name, list, active) VALUES ('Yacopí', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Yacuanquer', 'Nariño', TRUE);
insert into lists (name, list, active) VALUES ('Yaguará', 'Huila', TRUE);
insert into lists (name, list, active) VALUES ('Yalí', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Yarumal', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Yolombó', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Yondó', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Yopal', 'Casanare', TRUE);
insert into lists (name, list, active) VALUES ('Yotoco', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Yumbo', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Zambrano', 'Bolívar', TRUE);
insert into lists (name, list, active) VALUES ('Zapatoca', 'Santander', TRUE);
insert into lists (name, list, active) VALUES ('Zapayán', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Zaragoza', 'Antioquia', TRUE);
insert into lists (name, list, active) VALUES ('Zarzal', 'Valle del Cauca', TRUE);
insert into lists (name, list, active) VALUES ('Zetaquirá', 'Boyacá', TRUE);
insert into lists (name, list, active) VALUES ('Zipacón', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Zipaquirá', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Zona Bananera', 'Magdalena', TRUE);
insert into lists (name, list, active) VALUES ('Belén De Bajirá', 'Chocó', TRUE);
insert into lists (name, list, active) VALUES ('Caqueza', 'Cundinamarca', TRUE);
insert into lists (name, list, active) VALUES ('Enciso', 'Santander', TRUE);