insert into lists (name, list, active) VALUES ('N/A', 'PEOPLE_REJECT_REASON', TRUE);
insert into lists (name, list, active) VALUES ('N/A', 'COMPANY_REJECT_REASON', TRUE);

insert into lists (name, list, active) VALUES ('AMAZONAS', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('ANTIOQUIA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('ARAUCA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('ATLANTICO', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('BOLIVAR', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('BOYACA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('CALDAS', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('CAQUETA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('CASANARE', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('CAUCA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('CESAR', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('CHOCO', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('CORDOBA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('CUNDINAMARCA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('GUAINIA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('GUAVIARE', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('HUILA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('LA GUAJIRA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('MAGDALENA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('META', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('NARIÑO', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('NORTE DE SANTANDER', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('PUTUMAYO', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('QUINDIO', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('RISARALDA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('SAN ANDRES Y PROVIDENCIA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('SANTANDER', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('SUCRE', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('TOLIMA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('VALLE DEL CAUCA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('VAUPES', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('VICHADA', 'DEPT', TRUE);
insert into lists (name, list, active) VALUES ('ABEJORRAL', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ÁBREGO', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('ABRIAQUÍ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ACACÍAS', 'META', TRUE);
insert into lists (name, list, active) VALUES ('ACANDÍ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('ACEVEDO', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('ACHÍ', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('AGRADO', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('AGUA DE DIOS', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('AGUACHICA', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('AGUADA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('AGUADAS', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('AGUAZUL', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('AGUSTÍN CODAZZI', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('AIPE', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('ALBÁN', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('ALBÁN', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('ALBANIA', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('ALBANIA', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('ALBANIA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('ALCALÁ', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ALDANA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('ALEJANDRÍA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ALGARROBO', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('ALGECIRAS', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('ALMAGUER', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ALMEIDA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('ALPUJARRA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('ALTAMIRA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('ALTO BAUDÓ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('ALTOS DEL ROSARIO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('ALVARADO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('AMAGÁ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('AMALFI', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('AMBALEMA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('ANAPOIMA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('ANCUYÁ', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('ANDALUCÍA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ANDES', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ANGELÓPOLIS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ANGOSTURA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ANOLAIMA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('ANORÍ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ANSERMA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('ANSERMANUEVO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ANZÁ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ANZOÁTEGUI', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('APARTADÓ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('APÍA', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('APULO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('AQUITANIA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('ARACATACA', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('ARANZAZU', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('ARATOCA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('ARAUCA', 'ARAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ARAUQUITA', 'ARAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ARBELÁEZ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('ARBOLEDA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('ARBOLEDAS', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('ARBOLETES', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ARCABUCO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('ARENAL', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('ARGELIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ARGELIA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ARGELIA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ARIGUANÍ', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('ARJONA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('ARMENIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ARMENIA', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('ARMERO GUAYABAL', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('ARROYOHONDO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('ASTREA', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('ATACO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('ATRATO', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('AYAPEL', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('BAGADÓ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('BAHÍA SOLANO', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('BAJO BAUDÓ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('BALBOA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('BALBOA', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('BARANOA', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('BARAYA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('BARBACOAS', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('BARBOSA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('BARBOSA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('BARICHARA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('BARRANCA DE UPÍA', 'META', TRUE);
insert into lists (name, list, active) VALUES ('BARRANCABERMEJA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('BARRANCAS', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('BARRANCO DE LOBA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('BARRANCO MINAS', 'GUAINIA', TRUE);
insert into lists (name, list, active) VALUES ('BARRANQUILLA', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('BECERRIL', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('BELALCÁZAR', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('BELÉN', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('BELÉN', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('BELÉN DE LOS ANDAQUÍE', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('BELÉN DE UMBRÍA', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('BELLO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('BELMIRA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('BELTRÁN', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('BERBEO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('BETANIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('BETÉITIVA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('BETULIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('BETULIA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('BITUIMA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('BOAVITA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('BOCHALEMA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('BOGOTÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('BOJACÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('BOJAYÁ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('BOLÍVAR', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('BOLÍVAR', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('BOLÍVAR', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('BOSCONIA', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('BOYACÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('BRICEÑO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('BRICEÑO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('BUCARAMANGA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('BUCARASICA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('BUENAVENTURA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('BUENAVISTA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('BUENAVISTA', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('BUENAVISTA', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('BUENAVISTA', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('BUENOS AIRES', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('BUESACO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('BUGALAGRANDE', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('BURITICÁ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('BUSBANZÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CABRERA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CABRERA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CABUYARO', 'META', TRUE);
insert into lists (name, list, active) VALUES ('CACAHUAL', 'GUAINIA', TRUE);
insert into lists (name, list, active) VALUES ('CÁCERES', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CACHIPAY', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CÁCHIRA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CÁCOTA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CAICEDO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CAICEDONIA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('CAIMITO', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('CAJAMARCA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('CAJIBÍO', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('CAJICÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CALAMAR', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('CALAMAR', 'GUAVIARE', TRUE);
insert into lists (name, list, active) VALUES ('CALARCÁ', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('CALDAS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CALDAS', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CALDONO', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('CALI', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('CALIFORNIA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CALIMA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('CALOTO', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('CAMPAMENTO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CAMPO DE LA CRUZ', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('CAMPOALEGRE', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('CAMPOHERMOSO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CANALETE', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('CANDELARIA', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('CANDELARIA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('CANTAGALLO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('CAÑASGORDAS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CAPARRAPÍ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CAPITANEJO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CÁQUEZA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CARACOLÍ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CARAMANTA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CARCASÍ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CAREPA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CARMEN DE APICALÁ', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('CARMEN DE CARUPA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CARMEN DEL DARIÉN', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('CAROLINA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CARTAGENA DE INDIAS', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('CARTAGENA DEL CHAIRÁ', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('CARTAGO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('CARURÚ', 'VAUPES', TRUE);
insert into lists (name, list, active) VALUES ('CASABIANCA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('CASTILLA LA NUEVA', 'META', TRUE);
insert into lists (name, list, active) VALUES ('CAUCASIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CEPITÁ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CERETÉ', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('CERINZA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CERRITO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CERRO DE SAN ANTONIO', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('CÉRTEGUI', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('CHACHAGÜÍ', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('CHAGUANÍ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CHALÁN', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('CHÁMEZA', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('CHAPARRAL', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('CHARALÁ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CHARTA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CHÍA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CHIGORODÓ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CHIMA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CHIMÁ', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('CHIMICHAGUA', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('CHINÁCOTA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CHINAVITA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CHINCHINÁ', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('CHINÚ', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('CHIPAQUE', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CHIPATÁ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CHIQUINQUIRÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CHÍQUIZA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CHIRIGUANÁ', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('CHISCAS', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CHITA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CHITAGÁ', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CHITARAQUE', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CHIVATÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CHIVOLO', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('CHIVOR', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CHOACHÍ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CHOCONTÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CICUCO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('CIÉNAGA', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('CIÉNAGA DE ORO', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('CIÉNEGA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CIMITARRA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CIRCASIA', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('CISNEROS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CIUDAD BOLÍVAR', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CLEMENCIA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('COCORNÁ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('COELLO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('COGUA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('COLOMBIA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('COLÓN', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('COLÓN', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('COLOSÓ', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('CÓMBITA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CONCEPCIÓN', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CONCEPCIÓN', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CONCORDIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('CONCORDIA', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('CONDOTO', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('CONFINES', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CONSACÁ', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('CONTADERO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('CONTRATACIÓN', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CONVENCIÓN', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('COPACABANA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('COPER', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CÓRDOBA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('CÓRDOBA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('CÓRDOBA', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('CORINTO', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('COROMORO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('COROZAL', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('CORRALES', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('COTA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('COTORRA', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('COVARACHÍA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('COVEÑAS', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('COYAIMA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('CRAVO NORTE', 'ARAUCA', TRUE);
insert into lists (name, list, active) VALUES ('CUASPÚD', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('CUBARÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CUBARRAL', 'META', TRUE);
insert into lists (name, list, active) VALUES ('CUCAITA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CUCUNUBÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('CÚCUTA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CUCUTILLA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CUÍTIVA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('CUMARAL', 'META', TRUE);
insert into lists (name, list, active) VALUES ('CUMARIBO', 'VICHADA', TRUE);
insert into lists (name, list, active) VALUES ('CUMBAL', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('CUMBITARA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('CUNDAY', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('CURILLO', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('CURITÍ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('CURUMANÍ', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('DABEIBA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('DAGUA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('DIBULLA', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('DISTRACCIÓN', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('DOLORES', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('DONMATÍAS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('DOSQUEBRADAS', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('DUITAMA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('DURANIA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('EBÉJICO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('EL ÁGUILA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('EL BAGRE', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('EL BANCO', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('EL CAIRO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('EL CALVARIO', 'META', TRUE);
insert into lists (name, list, active) VALUES ('EL CANTÓN DEL SAN PAB', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('EL CARMEN', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('EL CARMEN DE ATRATO', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('EL CARMEN DE BOLÍVAR', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('EL CARMEN DE CHUCURÍ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('EL CARMEN DE VIBORAL', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('EL CASTILLO', 'META', TRUE);
insert into lists (name, list, active) VALUES ('EL CERRITO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('EL CHARCO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('EL COCUY', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('EL COLEGIO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('EL COPEY', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('EL DONCELLO', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('EL DORADO', 'META', TRUE);
insert into lists (name, list, active) VALUES ('EL DOVIO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('EL ENCANTO', 'AMAZONAS', TRUE);
insert into lists (name, list, active) VALUES ('EL ESPINO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('EL GUACAMAYO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('EL GUAMO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('EL LITORAL DEL SAN JUAN', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('EL MOLINO', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('EL PASO', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('EL PAUJÍL', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('EL PEÑOL', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('EL PEÑÓN', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('EL PEÑÓN', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('EL PEÑÓN', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('EL PIÑÓN', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('EL PLAYÓN', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('EL RETÉN', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('EL RETORNO', 'GUAVIARE', TRUE);
insert into lists (name, list, active) VALUES ('EL ROBLE', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('EL ROSAL', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('EL ROSAL', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('EL ROSARIO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('EL SANTUARIO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('EL TABLÓN DE GÓMEZ', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('EL TAMBO', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('EL TAMBO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('EL TARRA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('EL ZULIA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('ELÍAS', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('ENCINO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('ENCISO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('ENTRERRÍOS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ENVIGADO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ESPINAL', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('FACATATIVÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('FALAN', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('FILADELFIA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('FILANDIA', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('FIRAVITOBA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('FLANDES', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('FLORENCIA', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('FLORENCIA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('FLORESTA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('FLORIÁN', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('FLORIDA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('FLORIDABLANCA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('FÓMEQUE', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('FONSECA', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('FORTUL', 'ARAUCA', TRUE);
insert into lists (name, list, active) VALUES ('FOSCA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('FRANCISCO PIZARRO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('FREDONIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('FRESNO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('FRONTINO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('FUENTE DE ORO', 'META', TRUE);
insert into lists (name, list, active) VALUES ('FUNDACIÓN', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('FUNES', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('FUNZA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('FÚQUENE', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('FUSAGASUGÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GACHALÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GACHANCIPÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GACHANTIVÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('GACHETÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GALÁN', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('GALAPA', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('GALERAS', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('GAMA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GAMARRA', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('GÁMBITA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('GÁMEZA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('GARAGOA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('GARZÓN', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('GÉNOVA', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('GIGANTE', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('GINEBRA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('GIRALDO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('GIRARDOT', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GIRARDOTA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('GIRÓN', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('GÓMEZ PLATA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('GONZÁLEZ', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('GRAMALOTE', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('GRANADA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('GRANADA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GRANADA', 'META', TRUE);
insert into lists (name, list, active) VALUES ('GUACA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('GUACAMAYAS', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('GUACARÍ', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('GUACHENÉ', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('GUACHETÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GUACHUCAL', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('GUADALAJARA DE BUGA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('GUADALUPE', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('GUADALUPE', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('GUADALUPE', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('GUADUAS', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GUAITARILLA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('GUALMATÁN', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('GUAMAL', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('GUAMAL', 'META', TRUE);
insert into lists (name, list, active) VALUES ('GUAMO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('GUAPÍ', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('GUAPOTÁ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('GUARANDA', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('GUARNE', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('GUASCA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GUATAPÉ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('GUATAQUÍ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GUATAVITA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GUATEQUE', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('GUÁTICA', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('GUAVATÁ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('GUAYABAL DE SÍQUIMA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GUAYABETAL', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('GUAYATÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('GÜEPSA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('GUTIÉRREZ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('HACARÍ', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('HATILLO DE LOBA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('HATO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('HATO COROZAL', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('HATONUEVO', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('HELICONIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('HERRÁN', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('HERVEO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('HISPANIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('HOBO', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('HONDA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('IBAGUÉ', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('ICONONZO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('ILES', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('IMUÉS', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('INÍRIDA', 'GUAINIA', TRUE);
insert into lists (name, list, active) VALUES ('INZÁ', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('IPIALES', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('ÍQUIRA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('ISNOS', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('ISTMINA', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('ITAGÜÍ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ITUANGO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('IZA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('JAMBALÓ', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('JAMUNDÍ', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('JARDÍN', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('JENESANO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('JERICÓ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('JERICÓ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('JERUSALÉN', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('JESÚS MARÍA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('JORDÁN', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('JUAN DE ACOSTA', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('JUNÍN', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('JURADÓ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('LA APARTADA', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('LA ARGENTINA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('LA BELLEZA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('LA CALERA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('LA CAPILLA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('LA CEJA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('LA CELIA', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('LA CHORRERA', 'AMAZONAS', TRUE);
insert into lists (name, list, active) VALUES ('LA CRUZ', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('LA CUMBRE', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('LA DORADA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('LA ESPERANZA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('LA ESTRELLA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('LA FLORIDA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('LA GLORIA', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('LA GUADALUPE', 'GUAINIA', TRUE);
insert into lists (name, list, active) VALUES ('LA JAGUA DE IBIRICO', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('LA JAGUA DEL PILAR', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('LA LLANADA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('LA MACARENA', 'META', TRUE);
insert into lists (name, list, active) VALUES ('LA MERCED', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('LA MESA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('LA MONTAÑITA', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('LA PALMA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('LA PAZ', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('LA PAZ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('LA PEDRERA', 'AMAZONAS', TRUE);
insert into lists (name, list, active) VALUES ('LA PEÑA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('LA PINTADA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('LA PLATA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('LA PLAYA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('LA PRIMAVERA', 'VICHADA', TRUE);
insert into lists (name, list, active) VALUES ('LA SALINA', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('LA SIERRA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('LA TEBAIDA', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('LA TOLA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('LA UNION', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('LA UNIÓN', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('LA UNIÓN', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('LA UNIÓN', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('LA UVITA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('LA VEGA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('LA VEGA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('LA VICTORIA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('LA VICTORIA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('LA VICTORIA', 'AMAZONAS', TRUE);
insert into lists (name, list, active) VALUES ('LA VIRGINIA', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('LABATECA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('LABRANZAGRANDE', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('LANDÁZURI', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('LEBRIJA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('LEIVA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('LEJANÍAS', 'META', TRUE);
insert into lists (name, list, active) VALUES ('LENGUAZAQUE', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('LÉRIDA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('LETICIA', 'AMAZONAS', TRUE);
insert into lists (name, list, active) VALUES ('LÍBANO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('LIBORINA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('LINARES', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('LLORÓ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('LÓPEZ DE MICAY', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('LORICA', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('LOS ANDES', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('LOS CÓRDOBAS', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('LOS PALMITOS', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('LOS PATIOS', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('LOS SANTOS', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('LOURDES', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('LURUACO', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('MACANAL', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('MACARAVITA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('MACEO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('MACHETÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('MADRID', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('MAGANGUÉ', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('MAGÜÍ', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('MAHATES', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('MAICAO', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('MAJAGUAL', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('MÁLAGA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('MALAMBO', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('MALLAMA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('MANATÍ', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('MANAURE', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('MANAURE BALCÓN DEL CE', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('MANÍ', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('MANIZALES', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('MANTA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('MANZANARES', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('MAPIRIPÁN', 'META', TRUE);
insert into lists (name, list, active) VALUES ('MAPIRIPANA', 'GUAINIA', TRUE);
insert into lists (name, list, active) VALUES ('MARGARITA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('MARÍA LA BAJA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('MARINILLA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('MARIPÍ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('MARMATO', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('MARQUETALIA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('MARSELLA', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('MARULANDA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('MATANZA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('MEDELLÍN', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('MEDINA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('MEDIO ATRATO', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('MEDIO BAUDÓ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('MEDIO SAN JUAN', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('MELGAR', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('MERCADERES', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('MESETAS', 'META', TRUE);
insert into lists (name, list, active) VALUES ('MILÁN', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('MIRAFLORES', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('MIRAFLORES', 'GUAVIARE', TRUE);
insert into lists (name, list, active) VALUES ('MIRANDA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('MIRITÍ - PARANÁ', 'AMAZONAS', TRUE);
insert into lists (name, list, active) VALUES ('MISTRATÓ', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('MITÚ', 'VAUPES', TRUE);
insert into lists (name, list, active) VALUES ('MOCOA', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('MOGOTES', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('MOLAGAVITA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('MOMIL', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('MOMPÓS', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('MONGUA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('MONGUÍ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('MONIQUIRÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('MONTEBELLO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('MONTECRISTO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('MONTELÍBANO', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('MONTENEGRO', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('MONTERÍA', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('MONTERREY', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('MOÑITOS', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('MORALES', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('MORALES', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('MORELIA', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('MORICHAL', 'GUAINIA', TRUE);
insert into lists (name, list, active) VALUES ('MORROA', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('MOSQUERA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('MOSQUERA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('MOTAVITA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('MURILLO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('MURINDÓ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('MUTATÁ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('MUTISCUA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('MUZO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('NARIÑO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('NARIÑO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('NARIÑO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('NÁTAGA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('NATAGAIMA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('NECHÍ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('NECOCLÍ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('NEIRA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('NEIVA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('NEMOCÓN', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('NILO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('NIMAIMA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('NOBSA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('NOCAIMA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('NORCASIA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('NOROSÍ', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('NÓVITA', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('NUEVA GRANADA', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('NUEVO COLÓN', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('NUNCHÍA', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('NUQUÍ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('OBANDO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('OCAMONTE', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('OCAÑA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('OIBA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('OICATÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('OLAYA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('OLAYA HERRERA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('ONZAGA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('OPORAPA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('ORITO', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('OROCUÉ', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('ORTEGA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('OSPINA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('OTANCHE', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('OVEJAS', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('PACHAVITA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('PACHO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('PACOA', 'VAUPES', TRUE);
insert into lists (name, list, active) VALUES ('PÁCORA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('PADILLA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('PÁEZ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('PÁEZ', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('PAICOL', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('PAILITAS', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('PAIME', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('PAIPA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('PAJARITO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('PALERMO', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('PALESTINA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('PALESTINA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('PALMAR', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('PALMAR DE VARELA', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('PALMAS DEL SOCORRO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('PALMIRA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('PALMITO', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('PALOCABILDO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('PAMPLONA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('PAMPLONITA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('PANA PANA', 'GUAINIA', TRUE);
insert into lists (name, list, active) VALUES ('PANDI', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('PANQUEBA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('PAPUNAUA', 'VAUPES', TRUE);
insert into lists (name, list, active) VALUES ('PÁRAMO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('PARATEBUENO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('PASCA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('PASTO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('PATÍA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('PAUNA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('PAYA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('PAZ DE ARIPORO', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('PAZ DE RÍO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('PEDRAZA', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('PELAYA', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('PENSILVANIA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('PEÑOL', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('PEQUE', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('PEREIRA', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('PESCA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('PIAMONTE', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('PIEDECUESTA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('PIEDRAS', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('PIENDAMÓ', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('PIJAO', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('PIJIÑO DEL CARMEN', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('PINCHOTE', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('PINILLOS', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('PIOJÓ', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('PISBA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('PITAL', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('PITALITO', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('PIVIJAY', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('PLANADAS', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('PLANETA RICA', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('PLATO', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('POLICARPA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('POLONUEVO', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('PONEDERA', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('POPAYÁN', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('PORE', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('POTOSÍ', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('PRADERA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('PRADO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('PROVIDENCIA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('', 'ARCHIPIELAGO DE SAN ANDRES', TRUE);
insert into lists (name, list, active) VALUES ('PUEBLO BELLO', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('PUEBLO NUEVO', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('PUEBLO RICO', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('PUEBLORRICO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('PUEBLOVIEJO', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('PUENTE NACIONAL', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('PUERRES', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO ALEGRÍA', 'AMAZONAS', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO ARICA', 'AMAZONAS', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO ASÍS', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO BERRÍO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO BOYACÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO CAICEDO', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO CARREÑO', 'VICHADA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO COLOMBIA', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO COLOMBIA', 'GUAINIA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO CONCORDIA', 'META', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO ESCONDIDO', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO GAITÁN', 'META', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO GUZMÁN', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO LEGUÍZAMO', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO LIBERTADOR', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO LLERAS', 'META', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO LÓPEZ', 'META', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO NARE', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO NARIÑO', 'AMAZONAS', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO PARRA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO RICO', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO RICO', 'META', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO RONDÓN', 'ARAUCA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO SALGAR', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO SANTANDER', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO SANTANDER', 'AMAZONAS', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO TEJADA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO TRIUNFO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('PUERTO WILCHES', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('PULÍ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('PUPIALES', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('PURACÉ', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('PURIFICACIÓN', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('PURÍSIMA DE LA CONCEPCIÓN', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('QUEBRADANEGRA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('QUETAME', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('QUIBDÓ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('QUIMBAYA', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('QUINCHÍA', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('QUÍPAMA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('QUIPILE', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('RAGONVALIA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('RAMIRIQUÍ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('RÁQUIRA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('RECETOR', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('REGIDOR', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('REMEDIOS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('REMOLINO', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('REPELÓN', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('RESTREPO', 'META', TRUE);
insert into lists (name, list, active) VALUES ('RESTREPO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('RETIRO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('RICAURTE', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('RICAURTE', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('RÍO DE ORO', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('RÍO IRÓ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('RÍO QUITO', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('RÍO VIEJO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('RIOBLANCO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('RIOFRÍO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('RIOHACHA', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('RIONEGRO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('RIONEGRO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('RIOSUCIO', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('RIOSUCIO', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('RISARALDA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('RIVERA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('ROBERTO PAYÁN', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('ROLDANILLO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('RONCESVALLES', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('RONDÓN', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('ROSAS', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ROVIRA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('SABANA DE TORRES', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SABANAGRANDE', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('SABANALARGA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SABANALARGA', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('SABANALARGA', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('SABANAS DE SAN ÁNGEL', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('SABANETA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SABOYÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SÁCAMA', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('SÁCHICA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SAHAGÚN', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('SALADOBLANCO', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('SALAMINA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('SALAMINA', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('SALAZAR', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SALDAÑA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('SALENTO', 'QUINDIO', TRUE);
insert into lists (name, list, active) VALUES ('SALGAR', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAMACÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SAMANÁ', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('SAMANIEGO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('SAMPUÉS', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('SAN AGUSTÍN', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('SAN ALBERTO', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('SAN ANDRÉS', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SAN ANDRÉS DE CUERQUÍ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN ANDRÉS DE SOTAVENTO', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('SAN ANDRÉS DE TUMACO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('SAN ANTERO', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('SAN ANTONIO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('SAN ANTONIO DEL TEQUENDAMA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SAN BENITO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SAN BENITO ABAD', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('SAN BERNARDO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SAN BERNARDO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('SAN BERNARDO DEL VIENTO', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('SAN CALIXTO', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SAN CARLOS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN CARLOS', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('SAN CARLOS DE GUAROA', 'META', TRUE);
insert into lists (name, list, active) VALUES ('SAN CAYETANO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SAN CAYETANO', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SAN CRISTÓBAL', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SAN DIEGO', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('SAN EDUARDO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SAN ESTANISLAO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SAN FELIPE', 'GUAINIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN FERNANDO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SAN FRANCISCO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN FRANCISCO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SAN FRANCISCO', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('SAN GIL', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SAN JACINTO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SAN JACINTO DEL CAUCA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SAN JERÓNIMO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN JOAQUÍN', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SAN JOSÉ', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('SAN JOSÉ DE LA MONTAÑ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN JOSÉ DE MIRANDA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SAN JOSÉ DE PARE', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SAN JOSÉ DE URÉ', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('SAN JOSÉ DEL FRAGUA', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('SAN JOSÉ DEL GUAVIARE', 'GUAVIARE', TRUE);
insert into lists (name, list, active) VALUES ('SAN JOSÉ DEL PALMAR', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('SAN JUAN DE ARAMA', 'META', TRUE);
insert into lists (name, list, active) VALUES ('SAN JUAN DE BETULIA', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('SAN JUAN DE RIOSECO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SAN JUAN DE URABÁ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN JUAN DEL CESAR', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('SAN JUAN NEPOMUCENO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SAN JUANITO', 'META', TRUE);
insert into lists (name, list, active) VALUES ('SAN LORENZO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('SAN LUIS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN LUIS', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('SAN LUIS DE GACENO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SAN LUIS DE PALENQUE', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('SAN LUIS DE SINCÉ', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('SAN MARCOS', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('SAN MARTÍN', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('SAN MARTÍN', 'META', TRUE);
insert into lists (name, list, active) VALUES ('SAN MARTÍN DE LOBA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SAN MATEO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SAN MIGUEL', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SAN MIGUEL', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('SAN MIGUEL DE SEMA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SAN ONOFRE', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('SAN PABLO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SAN PABLO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('SAN PABLO DE BORBUR', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SAN PEDRO', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('SAN PEDRO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('SAN PEDRO DE CARTAGO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('SAN PEDRO DE LOS MILAGROS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN PEDRO DE URABÁ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN PELAYO', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('SAN RAFAEL', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN ROQUE', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN SEBASTIÁN', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('SAN SEBASTIÁN DE BUEN', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('SAN SEBASTIÁN DE MARIQUITA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('SAN VICENTE DE CHUCUR', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SAN VICENTE DEL CAGUÁ', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('SAN VICENTE DEL CAGUÁN', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('SAN VICENTE FERRER', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SAN ZENÓN', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('SANDONÁ', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('SANTA ANA', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA BÁRBARA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA BÁRBARA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('SANTA BÁRBARA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SANTA BÁRBARA DE PINT', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA CATALINA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SANTA FÉ DE ANTIOQUIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA HELENA DEL OPÓN', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SANTA ISABEL', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA LUCÍA', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('SANTA MARÍA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA MARÍA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA MARTA', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA ROSA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SANTA ROSA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA ROSA DE CABAL', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA ROSA DE OSOS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA ROSA DE VITERBO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA ROSA DEL SUR', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SANTA ROSALÍA', 'VICHADA', TRUE);
insert into lists (name, list, active) VALUES ('SANTA SOFÍA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SANTACRUZ', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('SANTANA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SANTANDER DE QUILICHAO', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('SANTIAGO', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SANTIAGO', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('SANTIAGO DE TOLÚ', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('SANTO DOMINGO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SANTO TOMÁS', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('SANTUARIO', 'RISARALDA', TRUE);
insert into lists (name, list, active) VALUES ('SAPUYES', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('SARAVENA', 'ARAUCA', TRUE);
insert into lists (name, list, active) VALUES ('SARDINATA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SASAIMA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SATIVANORTE', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SATIVASUR', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SEGOVIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SESQUILÉ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SEVILLA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('SIACHOQUE', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SIBATÉ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SIBUNDOY', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('SILOS', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SILVANIA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SILVIA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('SIMACOTA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SIMIJACA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SIMITÍ', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SINCELEJO', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('SIPÍ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('SITIONUEVO', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('SOACHA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SOATÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SOCHA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SOCORRO', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SOCOTÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SOGAMOSO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SOLANO', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('SOLEDAD', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('SOLITA', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('SOMONDOCO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SONSÓN', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SOPETRÁN', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('SOPLAVIENTO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('SOPÓ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SORA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SORACÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SOTAQUIRÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SOTARA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('SUAITA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SUAN', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('SUÁREZ', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('SUÁREZ', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('SUAZA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('SUBACHOQUE', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SUCRE', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('SUCRE', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SUCRE', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('SUESCA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SUPATÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SUPÍA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('SURATÁ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('SUSA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SUSACÓN', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SUTAMARCHÁN', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('SUTATAUSA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('SUTATENZA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TABIO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('TADÓ', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('TALAIGUA NUEVO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('TAMALAMEQUE', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('TÁMARA', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('TAME', 'ARAUCA', TRUE);
insert into lists (name, list, active) VALUES ('TÁMESIS', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('TAMINANGO', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('TANGUA', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('TARAIRA', 'VAUPES', TRUE);
insert into lists (name, list, active) VALUES ('TARAPACÁ', 'AMAZONAS', TRUE);
insert into lists (name, list, active) VALUES ('TARAZÁ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('TARQUI', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('TARSO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('TASCO', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TAURAMENA', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('TAUSA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('TELLO', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('TENA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('TENERIFE', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('TENJO', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('TENZA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TEORAMA', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('TERUEL', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('TESALIA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('TIBACUY', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('TIBANÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TIBASOSA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TIBIRITA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('TIBÚ', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('TIERRALTA', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('TIMANÁ', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('TIMBÍO', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('TIMBIQUÍ', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('TINJACÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TIPACOQUE', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TIQUISIO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('TITIRIBÍ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('TOCA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TOCAIMA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('TOCANCIPÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('TOGÜÍ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TOLEDO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('TOLEDO', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('TOLÚ VIEJO', 'SUCRE', TRUE);
insert into lists (name, list, active) VALUES ('TONA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('TÓPAGA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TOPAIPÍ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('TORIBÍO', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('TORO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('TOTA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TOTORÓ', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('TRINIDAD', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('TRUJILLO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('TUBARÁ', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('TUCHÍN', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('TULUÁ', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('TUNJA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TUNUNGUÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TÚQUERRES', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('TURBACO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('TURBANÁ', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('TURBO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('TURMEQUÉ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TUTA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('TUTAZÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('UBALÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('UBAQUE', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('ULLOA', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ÚMBITA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('UNE', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('UNGUÍA', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('UNIÓN PANAMERICANA', 'CHOCO', TRUE);
insert into lists (name, list, active) VALUES ('URAMITA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('URIBE', 'META', TRUE);
insert into lists (name, list, active) VALUES ('URIBIA', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('URRAO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('URUMITA', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('USIACURÍ', 'ATLANTICO', TRUE);
insert into lists (name, list, active) VALUES ('ÚTICA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('VALDIVIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('VALENCIA', 'CORDOBA', TRUE);
insert into lists (name, list, active) VALUES ('VALLE DE SAN JOSÉ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('VALLE DE SAN JUAN', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('VALLE DEL GUAMUEZ', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('VALLEDUPAR', 'CESAR', TRUE);
insert into lists (name, list, active) VALUES ('VALPARAÍSO', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('VALPARAÍSO', 'CAQUETA', TRUE);
insert into lists (name, list, active) VALUES ('VEGACHÍ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('VÉLEZ', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('VENADILLO', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('VENECIA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('VENECIA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('VENTAQUEMADA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('VERGARA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('VERSALLES', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('VETAS', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('VIANÍ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('VICTORIA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('VIGÍA DEL FUERTE', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('VIJES', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('VILLA CARO', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('VILLA DE LEYVA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('VILLA DE SAN DIEGO DE', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('VILLA DEL ROSARIO', 'NORTE DE SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('VILLA RICA', 'CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('VILLAGARZÓN', 'PUTUMAYO', TRUE);
insert into lists (name, list, active) VALUES ('VILLAGÓMEZ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('VILLAHERMOSA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('VILLAMARÍA', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('VILLANUEVA', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('VILLANUEVA', 'LA GUAJIRA', TRUE);
insert into lists (name, list, active) VALUES ('VILLANUEVA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('VILLANUEVA', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('VILLAPINZÓN', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('VILLARRICA', 'TOLIMA', TRUE);
insert into lists (name, list, active) VALUES ('VILLAVICENCIO', 'META', TRUE);
insert into lists (name, list, active) VALUES ('VILLAVIEJA', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('VILLETA', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('VIOTÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('VIRACACHÁ', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('VISTAHERMOSA', 'META', TRUE);
insert into lists (name, list, active) VALUES ('VITERBO', 'CALDAS', TRUE);
insert into lists (name, list, active) VALUES ('YACOPÍ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('YACUANQUER', 'NARIÑO', TRUE);
insert into lists (name, list, active) VALUES ('YAGUARÁ', 'HUILA', TRUE);
insert into lists (name, list, active) VALUES ('YALÍ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('YARUMAL', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('YAVARATÉ', 'VAUPES', TRUE);
insert into lists (name, list, active) VALUES ('YOLOMBÓ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('YONDÓ', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('YOPAL', 'CASANARE', TRUE);
insert into lists (name, list, active) VALUES ('YOTOCO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('YUMBO', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ZAMBRANO', 'BOLIVAR', TRUE);
insert into lists (name, list, active) VALUES ('ZAPATOCA', 'SANTANDER', TRUE);
insert into lists (name, list, active) VALUES ('ZAPAYÁN', 'MAGDALENA', TRUE);
insert into lists (name, list, active) VALUES ('ZARAGOZA', 'ANTIOQUIA', TRUE);
insert into lists (name, list, active) VALUES ('ZARZAL', 'VALLE DEL CAUCA', TRUE);
insert into lists (name, list, active) VALUES ('ZETAQUIRA', 'BOYACA', TRUE);
insert into lists (name, list, active) VALUES ('ZIPACÓN', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('ZIPAQUIRÁ', 'CUNDINAMARCA', TRUE);
insert into lists (name, list, active) VALUES ('ZONA BANANERA', 'MAGDALENA', TRUE);