insert into lists (name, list, active) VALUES ('Documento ilegible o incompleto', 'Documento de Identidad', TRUE);
insert into lists (name, list, active) VALUES ('Documento no está a nombre del Productor ', 'Documento de Identidad', TRUE);
insert into lists (name, list, active) VALUES ('No adjuntó el documento', 'Documento de Identidad', TRUE);
insert into lists (name, list, active) VALUES ('Número de identificación errado', 'Documento de Identidad', TRUE);
insert into lists (name, list, active) VALUES ('Identificación del anverso no corresponde con reverso', 'Documento de Identidad', TRUE);
insert into lists (name, list, active) VALUES ('Cedula incompleta', 'Documento de Identidad', TRUE);
insert into lists (name, list, active) VALUES ('Documento no vigente', 'Documento de Identidad', TRUE);
insert into lists (name, list, active) VALUES ('N/A', 'Documento de Identidad', TRUE);

insert into lists (name, list, active) VALUES ('Documento ilegible', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Documento no está a nombre del Productor', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('No adjuntó el documento', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Almacén no autorizado', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Fecha de la factura no está dentro del rango autorizado', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Factura con tachones y/o enmendaduras', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Factura 2 es la misma factura 1', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Facturador electronico con factura manual', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Factura sin firma', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Factura electronica no cumple requisitos de ley', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Factura en investigación', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Unidad de  medida no especificada', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('No Existe descripcion', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Sucursal no autorizada', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Producto no autorizado', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Factura sin nombre y/o identificación del productor', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Factura sin nit', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Valor total errado o sin valor total', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('Falta fecha de la factura', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - No indica que es factura electrónica de venta', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Los apellidos y nombre de quien preste el servicio o NIT del vendedor', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Los apellidos y nombre del comprador o NIT del comprador', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Incluir el sistema de numeración consecutiva', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Fecha y hora de generación', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Fecha y hora de expedición', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Cantidad y descripción específica de los bienes vendidos', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Valor total de la operación', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Forma de pago', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Medio de pago', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Indicar la calidad de retenedor del IVA', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Discriminación del IVA y la tarifa correspondiente', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Discriminación del Impuesto al Consumo y la tarifa correspondiente', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Incluir firma digital', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Indicar CUFE', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('FE no cumple Rley - Incluir código QR', 'Factura de Compra', TRUE);
insert into lists (name, list, active) VALUES ('N/A', 'Factura de Compra', TRUE);

insert into lists (name, list, active) VALUES ('Documento ilegible y/o incompleto', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('Documento no está a nombre del Productor', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('No adjuntó el documento', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('Se postula a mas de una cadena Productiva', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('Formato no corresponde al aprobado', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('declaración supera monto de activos $258.021.184', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('Entidad no acreditada para expedir certificado', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('Sin Fecha de Expedicion', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('Documento Tachone y/o Enmendaduras', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('cadena productiva no corresponde', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('Formato Incompleto', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('No especifica la cadena productiva', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('Sin firma', 'Certificado de Pequeño Productor', TRUE);
insert into lists (name, list, active) VALUES ('N/A', 'Certificado de Pequeño Productor', TRUE);

insert into lists (name, list, active) VALUES ('Certificación Juramentada', 'FILE_TYPE', TRUE);

insert into lists (name, list, active) VALUES ('Documento ilegible', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('Documento no está a nombre del Productor', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('No adjuntó el documento', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('Se postula a mas de una cadena Productiva', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('Formato no corresponde al aprobado', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('Declaración supera monto de activos $258.021.184', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('Entidad no acreditada para expedir certificado', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('Sin Fecha de Expedicion', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('Tachone y/o Enmendaduras', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('Cadena productiva no corresponde', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('Formato Incompleto', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('Sin firma', 'Certificación Juramentada', TRUE);
insert into lists (name, list, active) VALUES ('N/A', 'Certificación Juramentada', TRUE);

insert into lists (name, list, active) VALUES ('Certificado Bancario', 'FILE_TYPE', TRUE);

insert into lists (name, list, active) VALUES ('Documento ilegible y/o incompleto', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('Documento no está a nombre del Productor', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('No adjuntó el documento', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('Certificación bancaria no informa identificación y/o nombre', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('Certificación bancaria no informa el tipo y/o número de la cuenta bancaria', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('Certificación bancaria no es de un Banco', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('Certificación banco no está vigente', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('No se adjunta poder notarial para cobro', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('Documento con tachones y/o enmendaduras', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('Cuenta bancaria embargada', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('Certificación bancaria no activa', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('Certificado bancario pensional', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('Poder notarial con nom,bre y/o cc errrada', 'Certificado Bancario', TRUE);
insert into lists (name, list, active) VALUES ('N/A', 'Certificado Bancario', TRUE);

insert into lists (name, list, active) VALUES ('Documento ilegible y/o incompleto', 'RUT', TRUE);
insert into lists (name, list, active) VALUES ('No adjuntó el documento', 'RUT', TRUE);
insert into lists (name, list, active) VALUES ('RUT de Almacén no es igual al registrado en la factura', 'RUT', TRUE);
insert into lists (name, list, active) VALUES ('Rut 2 es el mismo rut 1', 'RUT', TRUE);
insert into lists (name, list, active) VALUES ('Rut no vigente', 'RUT', TRUE);
insert into lists (name, list, active) VALUES ('Rut no Especifica nombre del establecimiento comercial', 'RUT', TRUE);
insert into lists (name, list, active) VALUES ('Formulario de inscripión	Formulario en Blanco', 'RUT', TRUE);
insert into lists (name, list, active) VALUES ('Número de cédula registrado no coincide con soporte', 'RUT', TRUE);
insert into lists (name, list, active) VALUES ('N/A', 'RUT', TRUE);
