update lists set name = 'Guainía' where name = 'guainía';

update config_values set name = 'perc_Amazonas' WHERE name = 'perc_AMAZONAS';
update config_values set name = 'perc_Antioquia' WHERE name = 'perc_ANTIOQUIA';
update config_values set name = 'perc_Arauca' WHERE name = 'perc_ARAUCA';
update config_values set name = 'perc_Atlántico' WHERE name = 'perc_ATLANTICO';
update config_values set name = 'perc_Bolívar' WHERE name = 'perc_BOLIVAR';
update config_values set name = 'perc_Boyacá' WHERE name = 'perc_BOYACA';
update config_values set name = 'perc_Caldas' WHERE name = 'perc_CALDAS';
update config_values set name = 'perc_Caquetá' WHERE name = 'perc_CAQUETA';
update config_values set name = 'perc_Casanare' WHERE name = 'perc_CASANARE';
update config_values set name = 'perc_Cauca' WHERE name = 'perc_CAUCA';
update config_values set name = 'perc_Cesar' WHERE name = 'perc_CESAR';
update config_values set name = 'perc_Chocó' WHERE name = 'perc_CHOCO';
update config_values set name = 'perc_Cundinamarca' WHERE name = 'perc_CUNDINAMARCA';
update config_values set name = 'perc_Córdoba' WHERE name = 'perc_CORDOBA';
update config_values set name = 'perc_Guainía' WHERE name = 'perc_GUAINIA';
update config_values set name = 'perc_Guaviare' WHERE name = 'perc_GUAVIARE';
update config_values set name = 'perc_Huila' WHERE name = 'perc_HUILA';
update config_values set name = 'perc_La Guajira' WHERE name = 'perc_LA GUAJIRA';
update config_values set name = 'perc_Magdalena' WHERE name = 'perc_MAGDALENA';
update config_values set name = 'perc_Meta' WHERE name = 'perc_META';
update config_values set name = 'perc_Nariño' WHERE name = 'perc_NARIÑO';
update config_values set name = 'perc_Norte de Santander' WHERE name = 'perc_NORTE DE SANTANDER';
update config_values set name = 'perc_Putumayo' WHERE name = 'perc_PUTUMAYO';
update config_values set name = 'perc_Quindío' WHERE name = 'perc_QUINDIO';
update config_values set name = 'perc_Risaralda' WHERE name = 'perc_RISARALDA';
update config_values set name = 'perc_San Andrés y Providencia' WHERE name = 'perc_SAN ANDRES Y PROVIDENCIA';
update config_values set name = 'perc_Santander' WHERE name = 'perc_SANTANDER';
update config_values set name = 'perc_Sucre' WHERE name = 'perc_SUCRE';
update config_values set name = 'perc_Tolima' WHERE name = 'perc_TOLIMA';
update config_values set name = 'perc_Valle del Cauca' WHERE name = 'perc_VALLE DEL CAUCA';
update config_values set name = 'perc_Vaupés' WHERE name = 'perc_VAUPES';
update config_values set name = 'perc_Vichada' WHERE name = 'perc_VICHADA';